### ISSUE TITLE
老api读取失败

### ISSUE THREAD

**Issue by 3273576540** [KimigaiiWuyi/GenshinUID#117]

**Comment by 3273576540** [comment]
深渊信息读取老Api失败！
<built-in method with_traceback of TypeError object at 0x000001CDCC6862C0>
[2022-02-16 15:31:33,664 nonebot] ERROR: 深渊数据获取失败（Cookie失效/不公开信息）
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\GenshinUID\__init__.py", line 700, in get_info
    im = await draw_abyss0_pic(uid[0], nickname, image, uid[1])
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\GenshinUID\get_image.py", line 372, in draw_abyss0_pic
    if raw_data["retcode"] != 0:
TypeError: 'NoneType' object is not subscriptable

**Comment by KimigaiiWuyi** [comment]
先确认ck是否失效；
然后确认米游社是否更新深渊数据（今天新开深渊）

**Comment by 3273576540** [comment]
群里绑了ck的都能查体力但深渊报这个错
米游社已经显示满星了
查询上期深渊也报错

**Comment by KimigaiiWuyi** [comment]
pull试一下

**Comment by 3273576540** [comment]
ok解决了！
