### ISSUE TITLE
想请教一下，为什么私聊bot可以，群聊却报错，好像是信息发不出去，是还有哪里要设置参数吗？

### ISSUE THREAD

**Issue by CounterpickToWin** [KimigaiiWuyi/GenshinUID#123]
[ERROR] nonebot | Running matcher <Matcher from nonebot.plugins.GenshinUID-nonebot2-beta1, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "d:\anaconda\lib\site-packages\nonebot\plugins\GenshinUID-nonebot2-beta1\__init__.py", line 307, in send_cost
    await get_cost.send(im)
  File "d:\anaconda\lib\site-packages\nonebot\internal\matcher.py", line 449, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "d:\anaconda\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 247, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "d:\anaconda\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 175, in send
    return await bot.send_msg(**params)
  File "d:\anaconda\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 208, in call_api
    return await super().call_api(api, **data)
  File "d:\anaconda\lib\site-packages\nonebot\internal\adapter\bot.py", line 117, in call_api
    raise exception
  File "d:\anaconda\lib\site-packages\nonebot\internal\adapter\bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "d:\anaconda\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 108, in _call_api
    await ResultStore.fetch(bot.self_id, seq, self.config.api_timeout)
  File "d:\anaconda\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 2}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

**Comment by KimigaiiWuyi** [comment]
bot风控，qq号需要挂久一点

**Comment by CounterpickToWin** [comment]
可以了，确实是bot风控，感谢
