### ISSUE TITLE
查询功能出错

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#158]
```py
3-30 23:19:25 [ERROR] src | uid数据获取失败（Cookie失效/不公开信息）
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nb_cli\handlers\deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
> File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\genshin_uid\main.py", line 913, in get_info
    im = await draw_pic(uid[0], nickname, image, uid[1])
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\genshin_uid\get_image.py", line 1178, in draw_pic
    text_draw.text((490, 662), 'lv.' + str(raw_data['world_explorations'][1]['offerings'][0]['level']), text_color,
IndexError: list index out of range
```

**Comment by MingxuanGame** [comment]
这个是更新了层岩导致的
修复可以看hoshino的相关部分

**Comment by KimigaiiWuyi** [comment]
在画ui 今晚更新包含新地图的ui部分

**Comment by KimigaiiWuyi** [comment]
已修复
