### ISSUE TITLE
请教一下，nonebot2的插件引入相关的问题

### ISSUE THREAD

**Issue by EVAyo** [KimigaiiWuyi/GenshinUID#164]
## 环境
Python 3.8.10
nonebot2.0.0-beta.1
国内服务器

## 安装过程
1.nonebot2创建后在plugins文件夹内进行克隆
2.使用`nb plugin install nonebot-plugin-gocqhttp`安装了gocqhttp，**该步骤进行后可以收到QQ内消息**
3.在`pyproject.toml`文件配置如下,**该步骤进行后可以收到QQ内消息，但是无反应**
```
[tool.nonebot]
plugins = ["nonebot_plugin_gocqhttp"]
plugin_dirs = ["src/plugins/GenshinUID"]
```

## 相关日志
```
04-01 06:13:01 [ERROR] nonebot | Failed to import "genshin_uid"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/PaimonBot/./bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/PaimonBot/./src/plugins/GenshinUID/__init__.py", line 5, in <module>
    load_plugins(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/PaimonBot/./src/plugins/GenshinUID/genshin_uid/__init__.py", line 1, in <module>
    from .main import *
  File "/root/PaimonBot/./src/plugins/GenshinUID/genshin_uid/main.py", line 10, in <module>
    from .get_image import *
  File "/root/PaimonBot/./src/plugins/GenshinUID/genshin_uid/get_image.py", line 31, in <module>
    class CustomizeImage:
  File "/root/PaimonBot/./src/plugins/GenshinUID/genshin_uid/get_image.py", line 70, in CustomizeImage
    def get_bg_color(edit_bg: Image) -> tuple[int, int, int]:
TypeError: 'type' object is not subscriptable
04-01 06:13:01 [WARNING] src | 我们更推荐用本项目目录下的genshin_uid包作为插件加载，而不是整个项目
04-01 06:13:01 [WARNING] src | 本项目目录下的__init__.py仅作适配用
04-01 06:13:01 [SUCCESS] nonebot | Succeeded to import "GenshinUID"


```

**Comment by EVAyo** [comment]
> 151

感谢 已解决

**Comment by EVAyo** [comment]
> > 151
> 
> 感谢 已解决



> 参见 #151
