### ISSUE TITLE
米游社查询出错

### ISSUE THREAD

**Issue by tendapc** [KimigaiiWuyi/GenshinUID#196]
[2022-04-12 16:08:43,313] INFO in __init__: received event: message.group.normal
[2022-04-12 16:08:43,323 nonebot] INFO: Self: 9577749, Message -163607558 from 1836522@[群:10704721]: 'mys109731609'
2022-04-12 16:08:43 INFO Self: 9577749, Message -16365558 from 1837622@[群:1070721]: 'mys10973609'
[2022-04-12 16:08:43,331 genshinuid] INFO: Message -16365558 triggered send_mihoyo_bbs_info.
2022-04-12 16:08:43 INFO Message -163650758 triggered send_mihoyo_bbs_info.
[2022-04-12 16:08:43,870 nonebot] ERROR: 米游社数据获取失败（数据状态问题）
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\qqbot\HoshinoBot\hoshino\modules\GenshinUID\genshinuid.py", line 1010, in send_mihoyo_bbs_info
    im = await draw_pic(uid, ev.sender['nickname'], image, 3)
  File "C:\Users\Administrator\Desktop\qqbot\HoshinoBot\hoshino\modules\GenshinUID\mihoyo_libs\get_image.py", line 1077, in draw_pic
    retcode = await data_def.get_useable_cookies(uid, mode)
  File "C:\Users\Administrator\Desktop\qqbot\HoshinoBot\hoshino\modules\GenshinUID\mihoyo_libs\get_image.py", line 216, in get_useable_cookies
    await self.get_mihoyo_bbs_data()
  File "C:\Users\Administrator\Desktop\qqbot\HoshinoBot\hoshino\modules\GenshinUID\mihoyo_libs\get_image.py", line 232, in get_mihoyo_bbs_data
    self.uid = mys_data['data']['list'][0]['game_role_id']
IndexError: list index out of range
2022-04-12 16:08:43 ERROR 米游社数据获取失败（数据状态问题）
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\qqbot\HoshinoBot\hoshino\modules\GenshinUID\genshinuid.py", line 1010, in send_mihoyo_bbs_info
    im = await draw_pic(uid, ev.sender['nickname'], image, 3)
  File "C:\Users\Administrator\Desktop\qqbot\HoshinoBot\hoshino\modules\GenshinUID\mihoyo_libs\get_image.py", line 1077, in draw_pic
    retcode = await data_def.get_useable_cookies(uid, mode)
  File "C:\Users\Administrator\Desktop\qqbot\HoshinoBot\hoshino\modules\GenshinUID\mihoyo_libs\get_image.py", line 216, in get_useable_cookies
    await self.get_mihoyo_bbs_data()
  File "C:\Users\Administrator\Desktop\qqbot\HoshinoBot\hoshino\modules\GenshinUID\mihoyo_libs\get_image.py", line 232, in get_mihoyo_bbs_data
    self.uid = mys_data['data']['list'][0]['game_role_id']
IndexError: list index out of range
[2022-04-12 16:08:43,875 nonebot] INFO: Message -1636507558 is ignored
2022-04-12 16:08:43 INFO Message -1636507558 is ignored
2022-04-12 16:08:47 INFO received event: meta_event.heartbeat

**Comment by DaiShengSheng** [comment]
mys后面接的ID是米游社的ID，游戏内的uid查询前缀是uid，所以你应该使用uid109731609查询

**Comment by tendapc** [comment]
啊，丢人丢大了
