### ISSUE TITLE
获取活动信息错误

### ISSUE THREAD

**Issue by kickoutfromqqgroup** [KimigaiiWuyi/GenshinUID#214]
`04-28 14:48:21 [ERROR] src | 获取活动信息错误
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/python3.10/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/python3.10/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/python3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3.10/lib/python3.10/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/python3.10/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3.10/lib/python3.10/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/usr/local/python3.10/lib/python3.10/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3.10/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3.10/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/python3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
> File "/root/AnyaBot/./src/plugins/genshin_uid/main.py", line 224, in inner
    await func(**kwargs)
  File "/root/AnyaBot/./src/plugins/genshin_uid/main.py", line 428, in send_events
    await draw_event_pic()
  File "/root/AnyaBot/./src/plugins/genshin_uid/get_image.py", line 1781, in draw_event_pic
    value['time_data'], (255, 255, 255), genshin_font(42),
KeyError: 'time_data'
04-28 14:48:21 [INFO] nonebot | Matcher <Matcher from src.plugins.genshin_uid.main, type=message, priority=2, temp=False> running complete`

qq消息收到回复：发送错误'time_data', 请检查后台输出

服务器时区已经设置为
`root@ecs-207191:~# timedatectl
               Local time: Thu 2022-04-28 15:00:42 CST
           Universal time: Thu 2022-04-28 07:00:42 UTC
                 RTC time: Thu 2022-04-28 07:00:43    
                Time zone: Asia/Shanghai (CST, +0800) 
System clock synchronized: yes                        
              NTP service: active                     
          RTC in local TZ: no                         `

**Comment by KimigaiiWuyi** [comment]
趁着地脉活动又来了，赶紧修一修，之后如果还有问题，再开issuse吧
