### ISSUE TITLE
强制刷新log 报错

### ISSUE THREAD

**Issue by SonderXiaoming** [KimigaiiWuyi/GenshinUID#250]
`--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1081, in emit
    msg = self.format(record)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 925, in format
    return fmt.format(record)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 664, in format
    record.message = record.getMessage()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 8, in <module>
    bot.run(use_reloader=True, loop=asyncio.get_event_loop())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\__init__.py", line 61, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 222, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1270, in run
    loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\huannai\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\huannai\hoshino\modules\GenshinUID\genshinuid.py", line 343, in send_card_info
    logger.info(ev, f'UID{uid}获取角色数据成功！')
Message: <Event, {'anonymous': None, 'font': 0, 'group_id': 105733883, 'message': [{'type': 'text', 'data': {'text': ''}}], 'message_id': 1336241499, 'message_seq': 7401, 'message_type': 'group', 'post_type': 'message', 'raw_message': '强制刷新', 'self_id': 2434437952, 'sender': {'age': 0, 'area': '', 'card': '雨中流浪汗', 'level': '', 'nickname': '雨中流浪 汗', 'role': 'owner', 'sex': 'unknown', 'title': '', 'user_id': 1316864423}, 'sub_type': 'normal', 'time': 1654109890, 'user_id': 1316864423, 'to_me': False, 'prefix': '强制刷新', 'plain_text': '', 'norm_text': ''}>
Arguments: ('UID100153386获取角色数据成功！',)`
好像是格式写错了

**Comment by lgc2333** [comment]
这个问题应该不大，只是输出日志的时候出错了，如果不影响正常使用的话(逃2022年6月2日 上午3:03，SonderXiaoming ***@***.***>写道：

--- Logging error --- Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1081, in emit msg = self.format(record) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 925, in format return fmt.format(record) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 664, in format record.message = record.getMessage() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 369, in getMessage msg = msg % self.args TypeError: not all arguments converted during string formatting Call stack: File "run.py", line 8, in <module> bot.run(use_reloader=True, loop=asyncio.get_event_loop()) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\__init__.py", line 61, in run super().run(host=host, port=port, *args, **kwargs) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 222, in run self._server_app.run(host=host, port=port, *args, **kwargs) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1270, in run loop.run_until_complete(task) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete self.run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever super().run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever self._run_once() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once handle._run() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run self._context.run(self._callback, *self._args) File "C:\Users\Administrator\Desktop\huannai\hoshino\msghandler.py", line 28, in handle_message await service_func.func(bot, event) File "C:\Users\Administrator\Desktop\huannai\hoshino\modules\GenshinUID\genshinuid.py", line 343, in send_card_info logger.info(ev, f'UID{uid}获取角色数据成功！') Message: <Event, {'anonymous': None, 'font': 0, 'group_id': 105733883, 'message': [{'type': 'text', 'data': {'text': ''}}], 'message_id': 1336241499, 'message_seq': 7401, 'message_type': 'group', 'post_type': 'message', 'raw_message': '强制刷新', 'self_id': 2434437952, 'sender': {'age': 0, 'area': '', 'card': '雨中流浪汗', 'level': '', 'nickname': '雨中流浪 汗', 'role': 'owner', 'sex': 'unknown', 'title': '', 'user_id': 1316864423}, 'sub_type': 'normal', 'time': 1654109890, 'user_id': 1316864423, 'to_me': False, 'prefix': '强制刷新', 'plain_text': '', 'norm_text': ''}> Arguments: ('UID100153386获取角色数据成功！',)

好像是格式写错了

**Comment by KimigaiiWuyi** [comment]
`git pull`
~~ev!!!~~
