### ISSUE TITLE
插件更新后无法启动

### ISSUE THREAD

**Issue by Da2ns** [KimigaiiWuyi/GenshinUID#253]
日志
06-03 22:28:14 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gachalogs"
06-03 22:28:14 [ERROR] nonebot | Failed to import "genshin_uid"
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 17, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ysbot/./bot.py", line 24, in <module>
    nonebot.load_plugins("plugins")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/__init__.py", line 1005, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ysbot/plugins/GenshinUID/__init__.py", line 5, in <module>
    nonebot.load_plugins(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/__init__.py", line 1005, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ysbot/plugins/GenshinUID/genshin_uid/__init__.py", line 1, in <module>
    from .main import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "/home/ysbot/plugins/GenshinUID/genshin_uid/main.py", line 17, in <module>
    from .enkaToData.enkaToData import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 928, in get_code
  File "<frozen importlib._bootstrap_external>", line 379, in cache_from_source
TypeError: expected str, bytes or os.PathLike object, not NoneType
06-03 22:28:14 [SUCCESS] nonebot | Succeeded to import "GenshinUID"
06-03 22:28:14 [SUCCESS] nonebot | Running NoneBot...
06-03 22:28:15 [INFO] uvicorn | Started server process [600]
06-03 22:28:15 [INFO] uvicorn | Waiting for application startup.
06-03 22:28:15 [INFO] uvicorn | Application startup complete.
06-03 22:28:15 [INFO] uvicorn | Uvicorn running on http://172.18.0.3:6666 (Press CTRL+C to quit)
06-03 22:28:16 [INFO] uvicorn | ('172.18.0.4', 55294) - "WebSocket /cqhttp/ws/" [accepted]

尝试过重置安装，无法解决

**Comment by KimigaiiWuyi** [comment]
emmmm，可以把`.enkaToData.enkaToData import *` 这两行的.去掉
但有些人和我说去掉不能用，有些人去掉才能用（
稍后我改一下

**Comment by KimigaiiWuyi** [comment]
`nonebot2` a16分支的吧

**Comment by KimigaiiWuyi** [comment]
> 对

git pull后试试
