### ISSUE TITLE
查询词云失败

### ISSUE THREAD

**Issue by Da2ns** [KimigaiiWuyi/GenshinUID#262]
查询词云提示:获取失败，可能是Cookies失效或者未打开米游社角色详情开关。
cookie正常，直接查询可以返回角色和武器
报错日志
06-17 17:00:51 [ERROR] genshin_uid | 词云数据获取失败（Cookie失效/不公开信息）
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 22, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 256, in run
    uvicorn.run(
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 128, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 156, in _run_matcher
    await matcher.run(bot, event, state)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/matcher.py", line 597, in run
    await handler(self, bot, event, self.state)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/handler.py", line 64, in __call__
    await self.func(
> File "/home/ysbot/plugins/GenshinUID/genshin_uid/main.py", line 1196, in get_info    im = await draw_word_cloud(uid[0], image, uid[1])
  File "/home/ysbot/plugins/GenshinUID/genshin_uid/get_image.py", line 516, in draw_word_cloud
    mask = np.array([Image.open(os.path.join(TEXT_PATH, 'wordcloudmask.png'))])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'PngImageFile'
06-17 17:00:51 [INFO] nonebot | Matcher <Matcher from genshin_uid.main, type=message, priority=2, temp=False> running complete

![Screenshot_20220617-170521_QQ](https://user-images.githubusercontent.com/19469933/174266298-dd4823ea-6e08-46b3-9e24-898896d531c5.png)

**Comment by KimigaiiWuyi** [comment]
老问题了，这个功能也许将会被删除

**Comment by Da2ns** [comment]
> 老问题了，一直没改 这个功能也许将会被删除

好吧😂

**Comment by TimeRainStarSky** [comment]
我这也查不了，报错如下：
FutureWarning: The input object of type 'PngImageFile' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'PngImageFile', or assign to an empty array created with `np.empty(correct_shape, dtype=
object)`.                                                          mask = np.array([Image.open(os.path.join(TEXT_PATH, 'wordcloudmask.png'))])

**Comment by KimigaiiWuyi** [comment]
修了一部分，`git pull`后应该能使用了
