### ISSUE TITLE
哈哈，我又带来了一个新的问题，查询角色材料时报错了

### ISSUE THREAD

**Issue by 1055169799** [KimigaiiWuyi/GenshinUID#272]
群员发现的
![image](https://user-images.githubusercontent.com/41286675/177290183-7133b1e1-eef8-44d3-96b1-cf6121645feb.png)
然后我试了一下也是一样
![image](https://user-images.githubusercontent.com/41286675/177290242-756e7a7a-7c70-4da3-abf4-4be881e86791.png)

后台代码如下：

[2022-07-05 16:42:31,550 nonebot] ERROR: 获取材料信息错误
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
    yield
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 279, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\connection_pool.py", line 234, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_async\connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_backends\auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_backends\anyio.py", line 154, in open_tcp_stream
    stream = await TLSStream.wrap(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'info.minigg.cn'. (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\Genshinuid\genshinuid.py", line 179, in send_cost
    im = await char_wiki(message, 'costs')
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\Genshinuid\mihoyo_libs\get_mihoyo_bbs_data.py", line 610, in char_wiki
    data = await get_char_info(name, mode, level if mode == 'char' else None)
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\Genshinuid\mihoyo_libs\get_data.py", line 935, in get_char_info
    req = await client.get(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1661, in get
    return await self.request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1425, in request
    response = await self.send(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1510, in send
    response = await self._send_handling_auth(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1545, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1579, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1620, in _send_single_request
    ) = await transport.handle_async_request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 274, in handle_async_request
    (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'info.minigg.cn'. (_ssl.c:1129)
[2022-07-05 16:42:31,553 nonebot] INFO: Message -1322086440 is ignored

**Comment by KimigaiiWuyi** [comment]
等待minigg修复

**Comment by 1055169799** [comment]
> 等待minigg修复

原来是依赖于云端的其他服务的吗，了解了

**Comment by KimigaiiWuyi** [comment]
已修复
