### ISSUE TITLE
毕业度统计出现的问题

### ISSUE THREAD

**Issue by 1055169799** [KimigaiiWuyi/GenshinUID#275]
发完之后等了好久没啥反应，去后台看了是这样的：

[2022-07-10 10:30:58,574 nonebot] INFO: Self: 575075708, Message 1312090672 from 1055169799@[群:340595850]: '[CQ:at,qq=575075708] 毕业度统计'
[2022-07-10 10:30:58,574 Genshinuid] INFO: Message 1312090672 triggered send_charcard_list.
试作斩岩|海染砗磲|攻攻治
{'seq': '祭礼剑|海染砗磲|攻攻治', 'action': '符文治疗', 'crit_rate': 'any', 'atk': 1964.9120000000003, 'dmgBouns': 0, 'defArea': 0.5, 'resArea': 0.9, 'other': 0.73, 'other2': None, 'key': '攻击力', 'power': '153+1174', 'val': 7231.95}
7900.37681741266
西风秘典|如雷的盛怒|攻雷暴
{'seq': '四风原典|祭雷之人角斗士的终幕礼|攻雷暴', 'action': '满层E', 'crit_rate': 0.768, 'atk': 1945.6399999999999, 'dmgBouns': 0.936, 'defArea': 0.5405405405405406, 'resArea': 0.9, 'other': None, 'other2': None, 'key': '攻击力', 'power': 10.353, 'val': 48112.07}
19733.49637677703
绝弦|昔日宗室之仪|生雷暴
{'seq': '天空之翼|绝缘之旗印|充雷暴', 'action': 'Q吃乌羽', 'crit_rate': 0.8, 'atk': 1649.26, 'dmgBouns': 0.9455, 'defArea': 0.5, 'resArea': 0.9, 'other': 1.918, 'other2': None, 'key': '攻击力', 'power': 8.192, 'val': 51562.35}
28962.974026408003

{'seq': '薙草之稻光|华馆梦醒形骸记|防防防', 'action': '/', 'crit_rate': 'any', 'atk': 1631.7789599999999, 'dmgBouns': '/', 'defArea': 0.5, 'resArea': 0.9, 'other': 2.618, 'other2': 2511.0139999999997, 'key': '防御力', 'power': '防御力', 'val': 'any'}
683.532958984375
西风猎弓|昔日宗室之仪|充岩暴
{'seq': '西风猎弓|流放者|充岩暴', 'action': 'Q每次', 'crit_rate': 0.6025, 'atk': 1075.4, 'dmgBouns': '/', 'defArea': 0.5, 'resArea': 0.9, 'other': 1083.456, 'other2': 2.5309999999999997, 'key': '防御力', 'power': '防御力', 'val': 'any'}
542.0276489257812
证誓之明瞳|悠古的磐岩角斗士的终幕礼|攻岩暴
{'seq': '四风原典|悠古的磐岩角斗士的终幕礼|攻岩暴', 'action': 'Q每颗', 'crit_rate': 0.768, 'atk': 1906.72, 'dmgBouns': 0.976, 'defArea': 0.5, 'resArea': 0.9, 'other': None, 'other2': None, 'key': '攻击力', 'power': 1.8478999999999999, 'val': 6828.91}
5409.562550212378
暗巷闪光|冰风迷途的勇士|攻冰暴
{'seq': '西风剑|绝缘之旗印|攻冰暴', 'action': 'Q每段', 'crit_rate': 0.5275, 'atk': 1506.582, 'dmgBouns': 1.036, 'defArea': 0.5, 'resArea': 0.9, 'other': 2.28, 'other2': None, 'key': '攻击力', 'power': 1.649, 'val': 5360.37}
5887.505390043834
匣里龙吟|平息鸣雷的尊者|攻攻暴
{'seq': '雾切之回光|如雷的盛怒角斗士的终幕礼|攻雷暴', 'action': '重击', 'crit_rate': 0.73375, 'atk': 2251.1620000000003, 'dmgBouns': 1.016, 'defArea': 0.5, 'resArea': 0.9, 'other': None, 'other2': None, 'key': '攻击力', 'power': 1.7, 'val': 9608.3}
4262.662582964862
雨裁|绝缘之旗印|攻雷暴
{'seq': '狼的末路|绝缘之旗印|充雷暴', 'action': 'Q闪电链', 'crit_rate': 0.6025, 'atk': 1973.668, 'dmgBouns': 1.1855, 'defArea': 0.5, 'resArea': 1.025, 'other': 1.918, 'other2': None, 'key': '攻击力', 'power': 1.7280000000000002, 'val': 8423.08}
2147.142788807251

{'seq': '西风猎弓|冰风迷途的勇士角斗士的终幕礼|攻冰暴', 'action': 'Q满线圈', 'crit_rate': 0.5275, 'atk': 1649.848, 'dmgBouns': 1.254, 'defArea': 0.5, 'resArea': 0.9, 'other': None, 'other2': None, 'key': '攻击力', 'power': 5.4272, 'val': 21388.34}
4830.779362479958
弓藏|流浪大地的乐团|充攻暴
{'seq': '终末嗟叹之诗|昔日宗室之仪|攻火暴', 'action': 'Q总共', 'crit_rate': 0.6025, 'atk': 2310.3860000000004, 'dmgBouns': 0.666, 'defArea': 0.5, 'resArea': 0.9, 'other': 240, 'other2': None, 'key': '攻击力', 'power': 10.1088, 'val': 38608.26}
32773.582272716696

{'seq': '西风长枪|绝缘之旗印千岩牢固|充生暴', 'action': '满层护盾', 'crit_rate': 0.7, 'atk': 1492.18, 'dmgBouns': 0, 'defArea': 0.5, 'resArea': 0.9, 'other': 23024.546, 'other2': 2.224, 'key': '血量', 'power': '14.40+4829', 'val': 13854.62}
6795.36753125

{'seq': '狼的末路|翠绿之影|精攻治', 'action': 'Q每次治疗', 'crit_rate': 'any', 'atk': 2408.6240000000003, 'dmgBouns': 0.15, 'defArea': 0.5, 'resArea': 0.9, 'other': 443, 'other2': 0.358, 'key': '攻击力', 'power': '159.74+1280', 'val': 6963.19}
6118.564957879865
腐殖之剑|翠绿之影|精风暴
{'seq': '苍古自由之誓|翠绿之影|精精精', 'action': '扩散', 'crit_rate': 'any', 'atk': 1397, 'dmgBouns': 0, 'defArea': 0.5, 'resArea': 1.15, 'other': 1031, 'other2': 1.22, 'key': '元素精通', 'power': 'any', 'val': 7029.75}
4473.093565584743
嘟嘟可故事集|流浪大地的乐团|攻火暴
{'seq': '四风原典|流浪大地的乐团|攻火暴', 'action': '开Q重击蒸发', 'crit_rate': 0.768, 'atk': 1808.568, 'dmgBouns': 2.2560000000000002, 'defArea': 0.5, 'resArea': 0.9, 'other': 160, 'other2': None, 'key': '攻击力', 'power': 2.7292, 'val': 35355.26}
22329.924978992593
风鹰剑|昔日宗室之仪|生攻治
{'seq': '风鹰剑|昔日宗室之仪|充火暴', 'action': 'Q蒸发', 'crit_rate': 0.6025, 'atk': 1608.5, 'dmgBouns': 0.666, 'defArea': 0.5, 'resArea': 0.9, 'other': 80, 'other2': 1.985, 'key': '攻击力', 'power': 4.947, 'val': 39661.29}
19335.320346437005
试作金珀|翠绿之影流浪大地的乐团|攻风暴
{'seq': '祭礼残章|翠绿之影|充精精', 'action': '扩散', 'crit_rate': 'any', 'atk': 1059.8, 'dmgBouns': 0, 'defArea': 0.5, 'resArea': 1.15, 'other': 755, 'other2': None, 'key': '元素精通', 'power': 'any', 'val': 5973.98}
2917.455809326108
波乱月白经津|角斗士的终幕礼|攻水暴
{'seq': '波乱月白经津|来歆余响|攻水暴', 'action': 'E首刀+余响/无', 'crit_rate': 0.8, 'atk': 2076.022, 'dmgBouns': 0.986, 'defArea': 0.5, 'resArea': 0.9, 'other': 21238, 'other2': None, 'key': '攻击力', 'power': 1.0455, 'val': 10452.57}
7873.323751419974
天目影打刀|冰风迷途的勇士|攻冰暴
{'seq': '天目影打刀|冰风迷途的勇士|攻冰暴', 'action': '霜灭切割', 'crit_rate': 0.35, 'atk': 2155.3320000000003, 'dmgBouns': 0.796, 'defArea': 0.5, 'resArea': 0.9, 'other': None, 'other2': None, 'key': '攻击力', 'power': 2.0214, 'val': 10894.46}
11372.506870582858
龙脊长枪|冰风迷途的勇士|充冰暴
{'seq': '西风长枪|昔日宗室之仪|攻冰暴', 'action': 'Q每段', 'crit_rate': 0.7, 'atk': 1925.8300000000002, 'dmgBouns': 0.666, 'defArea': 0.5, 'resArea': 0.9, 'other': None, 'other2': None, 'key': '攻击力', 'power': 2.64, 'val': 7661.35}
7022.165727116178
不灭月华|被怜爱的少女|生生治
{'seq': '不灭月华|被怜爱的少女|生生治', 'action': 'Q瞬抬', 'crit_rate': 'any', 'atk': 1231.4, 'dmgBouns': 0, 'defArea': 0.5, 'resArea': 0.9, 'other': 36274.566000000006, 'other2': 0.608, 'key': '血量', 'power': '35.2+4335', 'val': 30923.39}
25829.807851721944

{'seq': '赤角石溃杵|华馆梦醒形骸记|防岩暴', 'action': '开Q重击连斩', 'crit_rate': 0.8, 'atk': 1233.8, 'dmgBouns': 0.706, 'defArea': 0.5, 'resArea': 0.9, 'other': 2431.065, 'other2': 1.22, 'key': '攻击力', 'power': 1.8019999999999998, 'val': 21056.9}
5923.57710464835
流浪乐章|绝缘之旗印|攻攻暴
{'seq': '流浪乐章|绝缘之旗印|攻水暴', 'action': 'Q暴击蒸发', 'crit_rate': 0.7402500000000001, 'atk': 1718.502, 'dmgBouns': 2.845, 'defArea': 0.5, 'resArea': 0.9, 'other': 1.82, 'other2': 80, 'key': '攻击力', 'power': 7.9632000000000005, 'val': 135118.76}
69251.694053671
天空之翼|如雷的盛怒|攻雷暴
{'seq': '绝弦|如雷的盛怒角斗士的终幕礼|攻雷暴', 'action': '奥兹攻击', 'crit_rate': 0.6025, 'atk': 1959.244, 'dmgBouns': 1.096, 'defArea': 0.5, 'resArea': 0.9, 'other': None, 'other2': None, 'key': '攻击力', 'power': 1.8869999999999998, 'val': 7689.05}
8317.456267861326
祭礼剑|沉沦之心昔日宗室之仪|攻水暴
{'seq': '祭礼剑|沉沦之心昔日宗室之仪|攻水暴', 'action': 'Q剑雨', 'crit_rate': 0.6025, 'atk': 1626.9360000000001, 'dmgBouns': 1.016, 'defArea': 0.5, 'resArea': 1.025, 'other': 17046.4, 'other2': 1.813, 'key': '攻击力', 'power': 1.1533, 'val': 4274.7}
2830.511437984371
无工之剑|角斗士的终幕礼|防岩暴
{'seq': '赤角石溃杵|华馆梦醒形骸记|防岩暴', 'action': '高达首刀', 'crit_rate': 0.7, 'atk': 1190.6, 'dmgBouns': 0.706, 'defArea': 0.5, 'resArea': 0.9, 'other': 2166.0889999999995, 'other2': None, 'key': '攻击力', 'power': 1.564, 'val': 16872.51}
7683.309508542694
衔珠海皇|绝缘之旗印|充攻攻
{'seq': '无工之剑|苍白之火染血的骑士道|攻物暴', 'action': 'Q横扫', 'crit_rate': 0.6025, 'atk': 2798.014, 'dmgBouns': 1.083, 'defArea': 0.5, 'resArea': 1.025, 'other': 1038.7, 'other2': None, 'key': '攻击力', 'power': 7.242000000000001, 'val': 47698.0}
24339.545397079706
绝弦|角斗士的终幕礼沉沦之心|攻水暴
{'seq': '冬极百星|沉沦之心流浪大地的乐团|攻水暴', 'action': '近战Q蒸发', 'crit_rate': 0.768, 'atk': 1916.294, 'dmgBouns': 1.024, 'defArea': 0.5, 'resArea': 0.9, 'other': 160, 'other2': None, 'key': '攻击力', 'power': 8.352, 'val': 120257.11}
92127.19812735796
试作古华|炽烈的炎之魔女|攻火暴
{'seq': '狼的末路|炽烈的炎之魔女|精火暴', 'action': 'Q蒸发', 'crit_rate': 0.6985, 'atk': 2193.228, 'dmgBouns': 1.041, 'defArea': 0.5, 'resArea': 0.9, 'other': 267, 'other2': None, 'key': '攻击力', 'power': 3.264, 'val': 37712.22}
22219.949877534003
祭礼弓|被怜爱的少女千岩牢固|生冰治
{'seq': '祭礼弓|被怜爱的少女千岩牢固|生生生', 'action': '长E盾值', 'crit_rate': 'any', 'atk': 1243.4, 'dmgBouns': 0, 'defArea': 0.5, 'resArea': 0.9, 'other': 31293.900000000005, 'other2': None, 'key': '血量', 'power': 0.153, 'val': 12716.64}
10533.5133421875
祭礼大剑|昔日宗室之仪|攻冰暴
{'seq': '狼的末路|冰风迷途的勇士昔日宗室之仪|攻冰暴', 'action': 'Q每段', 'crit_rate': 0.5275, 'atk': 2556.362, 'dmgBouns': 0.8160000000000001, 'defArea': 0.5, 'resArea': 0.9, 'other': None, 'other2': None, 'key': '攻击力', 'power': 3.0260000000000002, 'val': 14887.12}
6337.058064331214
渔获|悠古的磐岩昔日宗室之仪|攻岩暴
{'seq': '护摩之杖|悠古的磐岩昔日宗室之仪|生岩暴', 'action': 'Q开盾天星', 'crit_rate': 0.768, 'atk': 1611.1629599999999, 'dmgBouns': 1.104, 'defArea': 0.5, 'resArea': 1.05, 'other': 33670.369999999995, 'other2': None, 'key': '攻击力', 'power': 8.9972, 'val': 71732.51}
57709.77046576528
辰砂之纺锤|华馆梦醒形骸记|攻攻暴
{'seq': '辰砂之纺锤|华馆梦醒形骸记|防岩暴', 'action': 'E刹那之花', 'crit_rate': 0.6025, 'atk': 1157, 'dmgBouns': 0.994, 'defArea': 0.5, 'resArea': 0.9, 'other': 2579.8199999999997, 'other2': None, 'key': '攻击力', 'power': 3.2048, 'val': 17696.89}
12983.695676335952
雪葬的星银|苍白之火角斗士的终幕礼|精物暴
{'seq': '螭骨剑|角斗士的终幕礼|攻物暴', 'action': '普攻一段', 'crit_rate': 0.7405, 'atk': 1758.824, 'dmgBouns': 1.833, 'defArea': 0.5405405405405406, 'resArea': 0.9, 'other': None, 'other2': None, 'key': '攻击力', 'power': 1.7113, 'val': 10291.83}
6515.064695822591
试作星镰|绝缘之旗印|攻雷暴
{'seq': '薙草之稻光|绝缘之旗印|充雷暴', 'action': 'Q满层拔刀', 'crit_rate': 0.6025, 'atk': 2012.8694000000003, 'dmgBouns': 2.3216, 'defArea': 0.5, 'resArea': 0.9, 'other': 2.7890000000000006, 'other2': None, 'key': '攻击力', 'power': 11.4144, 'val': 75155.81}
57558.17545106305
天空之脊|炽烈的炎之魔女|充火暴
{'seq': '薙草之稻光|绝缘之旗印|充火暴', 'action': 'Q踩班蒸发', 'crit_rate': 0.6025, 'atk': 1936.61616, 'dmgBouns': 1.0745, 'defArea': 0.5, 'resArea': 0.9, 'other': 156, 'other2': 2.434, 'key': '攻击力', 'power': 2.38, 'val': 29492.71}
21335.52557357987
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C5372BD430>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C5372BD430>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C5372BD430>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C5372BD430>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C5372BD430>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C5372BD430>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C5372BD430>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C5372BD430>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C5372BD430>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[2022-07-10 10:31:00,639 Genshinuid] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when send_charcard_list handling message 1312090672.
[2022-07-10 10:31:00,639 Genshinuid] ERROR: <ActionFailed, retcode=100>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\Genshinuid\genshinuid.py", line 63, in send_charcard_list
    await bot.send(ev, str(im))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\__init__.py", line 251, in send
    return await self.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\__init__.py", line 219, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\api_impl.py", line 161, in call_action
    return _handle_api_result(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\api_impl.py", line 51, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=100>
[2022-07-10 10:31:00,640 nonebot] INFO: Message 1312090672 is ignored

**Comment by KimigaiiWuyi** [comment]
似乎是由于异步进程出错导致的
所有人都无法查询么

**Comment by 1055169799** [comment]
> 似乎是由于异步进程出错导致的 所有人都无法查询么

是的
![image](https://user-images.githubusercontent.com/41286675/178132459-89481105-c5cf-42dc-9280-5878eeedf523.png)
![image](https://user-images.githubusercontent.com/41286675/178132460-049a19bd-05e1-41c2-8b59-5240c7fc7a6d.png)
![image](https://user-images.githubusercontent.com/41286675/178132465-29cfd90e-1fbf-47ea-80c4-50dd5961897b.png)

**Comment by KimigaiiWuyi** [comment]
应该已修复
