### ISSUE TITLE
nb a16 分支出现导包错误

### ISSUE THREAD

**Issue by Jerry-FaGe** [KimigaiiWuyi/GenshinUID#279]
怀疑不同人情况不同是加载插件 `nonebot.load_plugins("src/GenshinUID")` 时的问题？

下面是日志
```
07-19 21:51:27 [ERROR] nonebot | Failed to import "genshin_uid"
Traceback (most recent call last):
  File "bot.py", line 42, in <module>
    nonebot.run(app="bot:app")
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/nonebot/__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 256, in run
    uvicorn.run(
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/uvicorn/config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/Jerry_FaGe/qqbot/bot.py", line 33, in <module>
    nonebot.load_plugins("src/GenshinUID")
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 1005, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/nonebot/plugin/__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/Jerry_FaGe/qqbot/src/GenshinUID/genshin_uid/__init__.py", line 1, in <module>
    from .main import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "/home/Jerry_FaGe/qqbot/src/GenshinUID/genshin_uid/main.py", line 18, in <module>
    from enkaToData.drawCharCard import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "/home/Jerry_FaGe/qqbot/src/GenshinUID/genshin_uid/enkaToData/drawCharCard.py", line 10, in <module>
    from .dmgCalc.dmgCalc import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/Jerry_FaGe/.local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 928, in get_code
  File "<frozen importlib._bootstrap_external>", line 379, in cache_from_source
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
试过把 `from .dmgCalc.dmgCalc import *` 的 `.` 删掉不过会报找不到 dmgCalc 这个包。

**Comment by MingxuanGame** [comment]
麻烦一下，请使用 `tree` 命令提供机器人目录的树状图，便于我们复现和诊断

**Comment by MingxuanGame** [comment]
更新了，可以试试
