### ISSUE TITLE
强制刷新报错

### ISSUE THREAD

**Issue by scxdhr1998** [KimigaiiWuyi/GenshinUID#282]
07-21 16:44:52 [ERROR] genshibot | 获取面板信息错误
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
> File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshin_uid/main.py", line 341, in inner
    await func(**kwargs)
  File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshin_uid/main.py", line 440, in send_card_info
    im = await enkaToData(uid)
  File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshin_uid/enkaToData/enkaToData.py", line 62, in enkaToData
    enka_data = json.loads(httpx.get(f'https://enka.shinshin.moe/u/{str(uid)}/__data.json').text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by scxdhr1998** [comment]
![8A644775-37AF-43B5-83BE-95CC54A52500](https://user-images.githubusercontent.com/72733583/180173696-255e6745-6fbf-4838-9cec-f5e516766d97.png)

**Comment by KimigaiiWuyi** [comment]
请`git pull`更新到最新版本之后再尝试

**Comment by KimigaiiWuyi** [comment]
`https://enka.shinshin.moe`已替换成`https://enka.network/`

**Comment by scxdhr1998** [comment]
没问题了👍🏻
