### ISSUE TITLE
强制刷新 命令出现问题

### ISSUE THREAD

**Issue by 1055169799** [KimigaiiWuyi/GenshinUID#288]
![image](https://user-images.githubusercontent.com/41286675/183333071-a17e4484-e4fe-4786-80db-b0c7ebfc74fd.png)

以下是后台日志

[2022-08-08 11:25:28,850 nonebot] INFO: Self: 575075708, Message 674581059 from 1055169799@[群:340595850]: '强制刷新'
[2022-08-08 11:25:28,852 Genshinuid] INFO: Message 674581059 triggered send_card_info.
[2022-08-08 11:25:29,863 nonebot] ERROR: 获取角色数据失败！
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\Genshinuid\genshinuid.py", line 399, in send_card_info
    im = await enkaToData(uid)
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\Genshinuid\enkaToData\enkaToData.py", line 59, in enkaToData
    enka_data = json.loads(httpx.get(f'https://enka.network/u/{str(uid)}/__data.json').text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by KimigaiiWuyi** [comment]
最近弄新版本忘了给老版本加header了，稍等

**Comment by KimigaiiWuyi** [comment]
尝试更新看是否修复

**Comment by 1055169799** [comment]
> 尝试更新看是否修复

[2022-08-08 11:52:09,677 nonebot] ERROR: 获取角色数据失败！
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\Genshinuid\genshinuid.py", line 399, in send_card_info
    im = await enkaToData(uid)
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\Genshinuid\enkaToData\enkaToData.py", line 59, in enkaToData
    enka_data = json.loads(httpx.get(url=f'https://enka.network/u/{str(uid)}/__data.json').text, headers={'User-Agent': 'GenshinUID/2.0'})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'headers'

**Comment by KimigaiiWuyi** [comment]
尴尬 github编辑器没高亮写错了，重新更新

**Comment by 1055169799** [comment]
> 尴尬 github编辑器没高亮写错了，重新更新

可以了
![image](https://user-images.githubusercontent.com/41286675/183337171-453798fb-93fe-42ce-9b22-33852c68090d.png)
