### ISSUE TITLE
【报错】路径错误

### ISSUE THREAD

**Issue by Z735803792** [KimigaiiWuyi/GenshinUID#313]
更新后，之前把插件放在dist-packages位置下的方法无法启用插件

```
08-30 22:57:24 [ERROR] nonebot | Failed to import "genshinuid_resource"
Traceback (most recent call last):
  File "/home/unb/nb2/bot.py", line 29, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/GenshinUID/__init__.py", line 5, in <module>
    load_plugins(os.path.dirname(__file__))
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 149, in load_plugin
    self._path_to_module_name(self._searched_plugin_names[name])
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 70, in _path_to_module_name
    rel_path = path.resolve().relative_to(Path(".").resolve())
  File "/usr/lib/python3.9/pathlib.py", line 939, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/usr/local/lib/python3.9/dist-packages/GenshinUID/genshinuid_resource/__init__.py' is not in the subpath of '/home/unb/nb2' OR one path is relative and the other is absolute.
```

**Comment by KimigaiiWuyi** [comment]
emmm, 只设定了相对路径导入
建议放在nb2官方推荐插件目录里
