### ISSUE TITLE
每月统计报错

### ISSUE THREAD

**Issue by scxdhr1998** [KimigaiiWuyi/GenshinUID#315]
```
08-31 15:32:30 [ERROR] genshibot | 访问https://hk4e-api.mihoyo.com/event/ys_ledger/monthInfo失败！
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/root/genshiBot/./genshibot/plugins/GenshinUID/utils/exception/handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshinuid_note/__init__.py", line 31, in send_monthly_data
    im = await award(uid)
  File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshinuid_note/note_text.py", line 25, in award
    data = await get_award(uid)
  File "/root/genshiBot/./genshibot/plugins/GenshinUID/utils/mhy_api/get_mhy_data.py", line 269, in get_award
    data = await _mhy_request(
> File "/root/genshiBot/./genshibot/plugins/GenshinUID/utils/mhy_api/get_mhy_data.py", line 428, in _mhy_request
    return await req.json()
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://hk4e-api.mihoyo.com/event/ys_ledger/monthInfo?act_id=e202009291139501&bind_region=cn_gf01&bind_uid=236341980&month=0&bbs_presentation_style=fullscreen&bbs_auth_required=true&utm_source=bbs&utm_medium=mys&utm_campaign=icon')
08-31 15:32:30 [ERROR] genshibot | 获取/发送每月统计失败
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
> File "/root/genshiBot/./genshibot/plugins/GenshinUID/utils/exception/handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshinuid_note/__init__.py", line 31, in send_monthly_data
    im = await award(uid)
  File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshinuid_note/note_text.py", line 26, in award
    nickname = data['data']['nickname']
KeyError: 'data'
```

**Comment by KimigaiiWuyi** [comment]
hoshino分支还是nonebot2分支

**Comment by scxdhr1998** [comment]
> hoshino分支还是nonebot2分支

nonebot2

**Comment by KimigaiiWuyi** [comment]
已修复
