### ISSUE TITLE
探索派遣包含五郎时“每日”指令报错

### ISSUE THREAD

**Issue by Baoer1** [KimigaiiWuyi/GenshinUID#334]
[ERROR] GenshinUID | 获取每日信息信息错误
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
> File "/home/ubuntu/Jerry/lib/python3.8/site-packages/GenshinUID/utils/exception/handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/GenshinUID/genshinuid_resin/__init__.py", line 104, in send_uid_info
    im = await get_resin_img(qid)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/GenshinUID/genshinuid_resin/draw_resin_card.py", line 86, in get_resin_img
    await asyncio.gather(*task)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/GenshinUID/genshinuid_resin/draw_resin_card.py", line 97, in _draw_all_resin_img
    resin_img = await draw_resin_img(uid)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/GenshinUID/genshinuid_resin/draw_resin_card.py", line 210, in draw_resin_img
    await asyncio.gather(*task_task)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/GenshinUID/genshinuid_resin/draw_resin_card.py", line 44, in _draw_task_img
    avatar_id = await enName_to_avatarId(char_en_name)
  File "/home/ubuntu/Jerry/lib/python3.8/site-packages/GenshinUID/utils/alias/enName_to_avatarId.py", line 11, in enName_to_avatarId
    avatar_id = enName_to_avatarId_data[en_name]
KeyError: 'Gorou'

试了下把五郎从探索派遣里移除，又恢复正常

**Comment by KimigaiiWuyi** [comment]
更新后查看是否修复

**Comment by Baoer1** [comment]
> 更新后查看是否修复

已经修复了
