### ISSUE TITLE
【报错】强制刷新失败

### ISSUE THREAD

**Issue by Z735803792** [KimigaiiWuyi/GenshinUID#345]
python3.9.13，大多情况下强制刷新没有问题，目前只知道强制刷新这个uid有问题

**强制刷新102003489**
bot:**发生错误 '10000072'，请检查后台输出。**
```
09-30 18:48:49 [ERROR] GenshinUID | 获取强制刷新信息错误
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
> File "/usr/local/lib/python3.9/dist-packages/GenshinUID/utils/exception/handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/GenshinUID/genshinuid_enka/__init__.py", line 222, in send_card_info
    im = await enka_to_data(uid)
  File "/usr/local/lib/python3.9/dist-packages/GenshinUID/utils/enka_api/enka_to_data.py", line 120, in enka_to_data
    avatarName = avatarId2Name[str(char['avatarId'])]
KeyError: '10000072'
```

**Comment by Z735803792** [comment]
已更新当前最新版本并没有解决，推测是无法识别新四星角色

**Comment by KimigaiiWuyi** [comment]
什么分支的?应该没有问题才对,检查一下是否更新成功了?
这个目录是有10000072的,去这个目录校验一下
![image](https://user-images.githubusercontent.com/55526518/193287490-9887a58a-e922-4b86-8511-c0192ba883d7.png)

**Comment by KimigaiiWuyi** [comment]
我推测你应该是没更新成功, 如果确认插件文件夹内没有资料或者改动的话,可以使用`gs强行强制更新`进行更新
![image](https://user-images.githubusercontent.com/55526518/193287840-e77e300e-55d1-484a-89d8-8c7c3f008776.png)

**Comment by Z735803792** [comment]
试了下强行强制更新命令（之前一直用upgrade更新来着）
```
10-02 03:56:44 [ERROR] nonebot | Running matcher <Matcher from GenshinUID.genshinuid_update, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.9/dist-packages/GenshinUID/genshinuid_update/__init__.py", line 84, in send_update_msg
    im = await update_genshinuid(level)
  File "/usr/local/lib/python3.9/dist-packages/GenshinUID/genshinuid_update/update.py", line 15, in update_genshinuid
    o = repo.remotes.origin
  File "/usr/local/lib/python3.9/dist-packages/git/util.py", line 1001, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin'
```

**Comment by Z735803792** [comment]
我用的更新方法是
`pip3 install git+https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git@nonebot2-beta1#egg=GenshinUID -U`
重启nb端自动下载，也没有办法解决，还是有这种报错

**Comment by Z735803792** [comment]
![image](https://user-images.githubusercontent.com/70925546/193426696-60dd8341-c7e5-4dfa-a979-4f09d064a158.png)
此目录下确实没有更新，我已通过手动下载替换解决）

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/70925546/193426696-60dd8341-c7e5-4dfa-a979-4f09d064a158.png) 此目录下确实没有更新，我已通过手动下载替换解决）

那有点奇怪,很有可能其他地方也并没有更新
可以试试`gs强行强制更新`这个命令看看
或者自己`git pull`看看是否有冲突警告
或者应该按照文档方式执行`pip3 install git+https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git@nonebot2-beta1#egg=GenshinUID -U`查看冲突警告

**Comment by Z735803792** [comment]
> > ![image](https://user-images.githubusercontent.com/70925546/193426696-60dd8341-c7e5-4dfa-a979-4f09d064a158.png) 此目录下确实没有更新，我已通过手动下载替换解决）
> 
> 那有点奇怪,很有可能其他地方也并没有更新 可以试试`gs强行强制更新`这个命令看看 或者自己`git pull`看看是否有冲突警告 或者应该按照文档方式执行`pip3 install git+https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git@nonebot2-beta1#egg=GenshinUID -U`查看冲突警告
`gs强行强制更新`报错是上面有的
至于更新命令，并没有警告，显示如下，但实际上没有更新。
```
root@lsRvGzPA14:/home/unb/nb2# pip3 install git+https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git@nonebot2-beta1#egg=GenshinUID -U
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting GenshinUID
  Cloning https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git (to revision nonebot2-beta1) to /tmp/pip-install-p2qlqw6a/genshinuid_6ea7c3e4e327412e9942cbdfaacf8ce9
  Running command git clone --filter=blob:none --quiet https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git /tmp/pip-install-p2qlqw6a/genshinuid_6ea7c3e4e327412e9942cbdfaacf8ce9
  Running command git checkout -b nonebot2-beta1 --track origin/nonebot2-beta1
  Switched to a new branch 'nonebot2-beta1'
  Branch 'nonebot2-beta1' set up to track remote branch 'nonebot2-beta1' from 'origin'.
  Resolved https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git to commit aeec83f982a0ea95b237540d57ce9a816480ba8e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: sqlalchemy>=1.4.39 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (1.4.39)Requirement already satisfied: aiohttp>=3.8.1 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (3.8.3)
Requirement already satisfied: sqlmodel>=0.0.8 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (0.0.8)
Requirement already satisfied: pillow>=9.2.0 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (9.2.0)
Requirement already satisfied: wordcloud>=1.8.2 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (1.8.2.2)
Requirement already satisfied: nonebot2>=2.0.0-beta.4 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (2.0.0b4)
Requirement already satisfied: scikit-learn>=1.1.2 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (1.1.2)Requirement already satisfied: shapely>=1.8.2 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (1.8.4)
Requirement already satisfied: nonebot-plugin-apscheduler>=0.1.4 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (0.1.4)
Requirement already satisfied: nonebot-adapter-onebot>=2.1.1 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (2.1.3)
Requirement already satisfied: aiofiles>=0.8.0 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (22.1.0)
Requirement already satisfied: gitpython>=3.1.27 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (3.1.27)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (4.11.1)
Requirement already satisfied: aiosqlite>=0.17.0 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (0.17.0)
Requirement already satisfied: fastapi-amis-admin>=0.2.1 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (0.2.1)
Requirement already satisfied: fastapi-user-auth>=0.2.1 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (0.2.1)
Requirement already satisfied: openpyxl>=3.0.10 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (3.0.10)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (4.9.1)
Requirement already satisfied: numpy>=1.23.1 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (1.23.2)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.9/dist-packages (from GenshinUID) (0.23.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.9/dist-packages (from aiohttp>=3.8.1->GenshinUID) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.9/dist-packages (from aiohttp>=3.8.1->GenshinUID) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/dist-packages (from aiohttp>=3.8.1->GenshinUID) (6.0.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp>=3.8.1->GenshinUID) (2.0.11)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp>=3.8.1->GenshinUID) (21.4.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp>=3.8.1->GenshinUID) (1.7.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from aiohttp>=3.8.1->GenshinUID) (1.3.0)
Requirement already satisfied: typing_extensions>=3.7.2 in /usr/local/lib/python3.9/dist-packages (from aiosqlite>=0.17.0->GenshinUID) (4.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.9/dist-packages (from beautifulsoup4>=4.11.1->GenshinUID) (2.3.1)
Requirement already satisfied: sqlalchemy-database<0.1.0,>=0.0.5 in /usr/local/lib/python3.9/dist-packages (from fastapi-amis-admin>=0.2.1->GenshinUID) (0.0.7)
Requirement already satisfied: python-multipart>=0.0.5 in /usr/local/lib/python3.9/dist-packages (from fastapi-amis-admin>=0.2.1->GenshinUID) (0.0.5)
Requirement already satisfied: fastapi>=0.68.0 in /usr/local/lib/python3.9/dist-packages (from fastapi-amis-admin>=0.2.1->GenshinUID) (0.78.0)
Requirement already satisfied: pydantic>=1.9 in /usr/local/lib/python3.9/dist-packages (from fastapi-user-auth>=0.2.1->GenshinUID) (1.9.2)
Requirement already satisfied: email-validator in /usr/local/lib/python3.9/dist-packages (from fastapi-user-auth>=0.2.1->GenshinUID) (1.2.1)
Requirement already satisfied: passlib in /usr/local/lib/python3.9/dist-packages (from fastapi-user-auth>=0.2.1->GenshinUID) (1.7.4)
Requirement already satisfied: bcrypt in /usr/local/lib/python3.9/dist-packages (from fastapi-user-auth>=0.2.1->GenshinUID) (4.0.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.9/dist-packages (from gitpython>=3.1.27->GenshinUID) (4.0.9)
Requirement already satisfied: sniffio in /usr/local/lib/python3.9/dist-packages (from httpx>=0.23.0->GenshinUID) (1.2.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from httpx>=0.23.0->GenshinUID) (2021.10.8)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /usr/local/lib/python3.9/dist-packages (from httpx>=0.23.0->GenshinUID) (1.5.0)
Requirement already satisfied: httpcore<0.16.0,>=0.15.0 in /usr/local/lib/python3.9/dist-packages (from httpx>=0.23.0->GenshinUID) (0.15.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in /usr/local/lib/python3.9/dist-packages (from nonebot-adapter-onebot>=2.1.1->GenshinUID) (1.0.3)
Requirement already satisfied: apscheduler<4.0.0,>=3.7.0 in /usr/local/lib/python3.9/dist-packages (from nonebot-plugin-apscheduler>=0.1.4->GenshinUID) (3.8.1)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in /usr/local/lib/python3.9/dist-packages (from nonebot2>=2.0.0-beta.4->GenshinUID) (2.4.2)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /usr/local/lib/python3.9/dist-packages (from nonebot2>=2.0.0-beta.4->GenshinUID) (0.6.0)
Requirement already satisfied: uvicorn[standard]<0.18.0,>=0.17.0 in /usr/local/lib/python3.9/dist-packages (from nonebot2>=2.0.0-beta.4->GenshinUID) (0.17.6)
Requirement already satisfied: tomlkit<1.0.0,>=0.10.0 in /usr/local/lib/python3.9/dist-packages (from nonebot2>=2.0.0-beta.4->GenshinUID) (0.11.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.9/dist-packages (from openpyxl>=3.0.10->GenshinUID) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=1.1.2->GenshinUID) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=1.1.2->GenshinUID) (1.1.0)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=1.1.2->GenshinUID) (1.8.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.9/dist-packages (from sqlalchemy>=1.4.39->GenshinUID) (1.1.2)
Requirement already satisfied: sqlalchemy2-stubs in /usr/local/lib/python3.9/dist-packages (from sqlmodel>=0.0.8->GenshinUID) (0.0.2a24)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/dist-packages (from wordcloud>=1.8.2->GenshinUID) (3.5.2)
Requirement already satisfied: setuptools>=0.7 in /usr/local/lib/python3.9/dist-packages (from apscheduler<4.0.0,>=3.7.0->nonebot-plugin-apscheduler>=0.1.4->GenshinUID) (59.8.0)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in /usr/local/lib/python3.9/dist-packages (from apscheduler<4.0.0,>=3.7.0->nonebot-plugin-apscheduler>=0.1.4->GenshinUID) (4.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.9/dist-packages (from apscheduler<4.0.0,>=3.7.0->nonebot-plugin-apscheduler>=0.1.4->GenshinUID) (2021.3)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.9/dist-packages (from apscheduler<4.0.0,>=3.7.0->nonebot-plugin-apscheduler>=0.1.4->GenshinUID) (1.16.0)
Requirement already satisfied: starlette==0.19.1 in /usr/local/lib/python3.9/dist-packages (from fastapi>=0.68.0->fastapi-amis-admin>=0.2.1->GenshinUID) (0.19.1)
Requirement already satisfied: anyio<5,>=3.4.0 in /usr/local/lib/python3.9/dist-packages (from starlette==0.19.1->fastapi>=0.68.0->fastapi-amis-admin>=0.2.1->GenshinUID) (3.5.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.9/dist-packages (from gitdb<5,>=4.0.1->gitpython>=3.1.27->GenshinUID) (5.0.0)
Requirement already satisfied: h11<0.13,>=0.11 in /usr/local/lib/python3.9/dist-packages (from httpcore<0.16.0,>=0.15.0->httpx>=0.23.0->GenshinUID) (0.12.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.9/dist-packages (from anyio<5,>=3.4.0->starlette==0.19.1->fastapi>=0.68.0->fastapi-amis-admin>=0.2.1->GenshinUID) (3.3)
Requirement already satisfied: python-dotenv>=0.10.4 in /usr/local/lib/python3.9/dist-packages (from pydantic>=1.9->fastapi-user-auth>=0.2.1->GenshinUID) (0.19.2)
Requirement already satisfied: asgiref>=3.4.0 in /usr/local/lib/python3.9/dist-packages (from uvicorn[standard]<0.18.0,>=0.17.0->nonebot2>=2.0.0-beta.4->GenshinUID) (3.5.0)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.9/dist-packages (from uvicorn[standard]<0.18.0,>=0.17.0->nonebot2>=2.0.0-beta.4->GenshinUID) (8.1.3)
Requirement already satisfied: websockets>=10.0 in /usr/local/lib/python3.9/dist-packages (from uvicorn[standard]<0.18.0,>=0.17.0->nonebot2>=2.0.0-beta.4->GenshinUID) (10.1)
Requirement already satisfied: watchgod>=0.6 in /usr/local/lib/python3.9/dist-packages (from uvicorn[standard]<0.18.0,>=0.17.0->nonebot2>=2.0.0-beta.4->GenshinUID) (0.7)
Requirement already satisfied: httptools>=0.4.0 in /usr/local/lib/python3.9/dist-packages (from uvicorn[standard]<0.18.0,>=0.17.0->nonebot2>=2.0.0-beta.4->GenshinUID) (0.4.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.9/dist-packages (from uvicorn[standard]<0.18.0,>=0.17.0->nonebot2>=2.0.0-beta.4->GenshinUID) (6.0)
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /usr/local/lib/python3.9/dist-packages (from uvicorn[standard]<0.18.0,>=0.17.0->nonebot2>=2.0.0-beta.4->GenshinUID) (0.16.0)
Requirement already satisfied: dnspython>=1.15.0 in /usr/local/lib/python3.9/dist-packages (from email-validator->fastapi-user-auth>=0.2.1->GenshinUID) (2.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud>=1.8.2->GenshinUID) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud>=1.8.2->GenshinUID) (3.0.7)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud>=1.8.2->GenshinUID) (4.33.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud>=1.8.2->GenshinUID) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud>=1.8.2->GenshinUID) (1.4.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud>=1.8.2->GenshinUID) (2.8.2)
Requirement already satisfied: pytz-deprecation-shim in /usr/local/lib/python3.9/dist-packages (from tzlocal!=3.*,>=2.0->apscheduler<4.0.0,>=3.7.0->nonebot-plugin-apscheduler>=0.1.4->GenshinUID) (0.1.0.post0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.9/dist-packages (from pytz-deprecation-shim->tzlocal!=3.*,>=2.0->apscheduler<4.0.0,>=3.7.0->nonebot-plugin-apscheduler>=0.1.4->GenshinUID) (2021.5)
```

**Comment by Z735803792** [comment]
今天更新尝试，有报错了
```
root@lsRvGzPA14:~# pip3 install git+https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git@nonebot2-beta1#egg=GenshinUID -U
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting GenshinUID
  Cloning https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git (to revision nonebot2-beta1) to /tmp/pip-install-fd684p2w/genshinuid_b637d18dd0424089b83c7c60703e7f20
  Running command git clone --filter=blob:none --quiet https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git /tmp/pip-install-fd684p2w/genshinuid_b637d18dd0424089b83c7c60703e7f20
  error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
  fatal: the remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git /tmp/pip-install-fd684p2w/genshinuid_b637d18dd0424089b83c7c60703e7f20 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git /tmp/pip-install-fd684p2w/genshinuid_b637d18dd0424089b83c7c60703e7f20 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
