### ISSUE TITLE
每月统计 数据除以0

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#346]
```py
10-02 00:57:59 [ERROR] src | 获取/发送每月统计失败
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\bot.py", line 38, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
> File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\utils\exception\handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\genshinuid_note\__init__.py", line 53, in send_monthly_pic
    im = await draw_note_img(uid)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\genshinuid_note\draw_note_card.py", line 61, in draw_note_img
    day_stone_percent = day_stone / lastday_stone
ZeroDivisionError: division by zero
```

**Comment by KimigaiiWuyi** [comment]
更新看看

**Comment by lgc2333** [comment]
已解决
