### ISSUE TITLE
刷新抽卡记录报错

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#349]
```py
10-04 20:19:13 [ERROR] src | 获取刷新抽卡记录信息错误
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\bot.py", line 38, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
> File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\utils\exception\handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\genshinuid_gachalog\__init__.py", line 128, in send_daily_info
    im = await save_gachalogs(uid)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\genshinuid_gachalog\get_gachalogs.py", line 37, in save_gachalogs
    raw_data = await get_gacha_log_by_authkey(uid, gachalogs_history)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\utils\mhy_api\get_mhy_data.py", line 96, in get_gacha_log_by_authkey
    if 'data' in raw_data and 'list' in raw_data['data']:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by KimigaiiWuyi** [comment]
pr呢pr呢pr呢

**Comment by lgc2333** [comment]
> pr呢pr呢pr呢

?

**Comment by lgc2333** [comment]
> > 
> 
> print一下raw_data看看

？？？我不知道咋回事突然又好了

**Comment by lgc2333** [comment]
下次遇到问题再reopen，我先close
