### ISSUE TITLE
刷新抽卡记录报错：发生错误 argument of type 'NoneType' is not iterable，请检查后台输出。

### ISSUE THREAD

**Issue by liujhs** [KimigaiiWuyi/GenshinUID#358]
`10-21 16:08:27 [ERROR] GenshinUID-nonebot2 | 获取刷新抽卡记录信息错误
Traceback (most recent call last):
  File "/root/anaconda3/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/anaconda3/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/anaconda3/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/root/anaconda3/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 688, in simple_run
    await handler(
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "/app/Nonebot2/./src/plugins/GenshinUID-nonebot2/GenshinUID/utils/exception/handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "/app/Nonebot2/./src/plugins/GenshinUID-nonebot2/GenshinUID/genshinuid_gachalog/__init__.py", line 128, in send_daily_info
    im = await save_gachalogs(uid)
  File "/app/Nonebot2/./src/plugins/GenshinUID-nonebot2/GenshinUID/genshinuid_gachalog/get_gachalogs.py", line 37, in save_gachalogs
    raw_data = await get_gacha_log_by_authkey(uid, gachalogs_history)
  File "/app/Nonebot2/./src/plugins/GenshinUID-nonebot2/GenshinUID/utils/mhy_api/get_mhy_data.py", line 64, in get_gacha_log_by_authkey
    if 'data' in authkey_rawdata and 'authkey' in authkey_rawdata['data']:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by KimigaiiWuyi** [comment]
校验一下Stoken看看

**Comment by liujhs** [comment]
> 校验一下Stoken看看

可以了，stoken过期了
