### ISSUE TITLE
疑似低星圣遗物造成的强制刷新失败

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#360]
```py
10-31 00:02:00 [ERROR] GenshinUID | 获取强制刷新信息错误
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\utils\exception\handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\__init__.py", line 280, in send_card_info
    im = await enka_to_card(uid)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\utils\enka_api\enka_to_card.py", line 33, in enka_to_card
    char_data_list = await enka_to_dict(uid, enka_data)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\utils\enka_api\enka_to_data.py", line 323, in enka_to_dict
    artifact_temp['reliquarySubstats'] = artifact['flat'][
KeyError: 'reliquarySubstats'
```

**Comment by lgc2333** [comment]
UID `250192694`

**Comment by KimigaiiWuyi** [comment]
已修复
![R4O0@41TQ FF7J60L1A(IRH](https://user-images.githubusercontent.com/55526518/200036842-57491e00-5eb4-417a-9e47-d2cea1e06fa1.PNG)
