### ISSUE TITLE
网页控制台 Admin 用户的默认密码

### ISSUE THREAD

**Issue by Jerry-FaGe** [KimigaiiWuyi/GenshinUID#364]
我找了半天文档和源码也没找到这个网页控制台 Admin 用户的默认密码。。。如果注册的第一个用户默认是管理员的话，我注册了一个新用户但他并没有管理员相关的权限而且 user_id 是 2 。

**Comment by KimigaiiWuyi** [comment]
账号:admin
密码:admin

**Comment by Jerry-FaGe** [comment]
> 账号:admin 密码:admin

感谢，成功了。还是建议在文档或什么地方标注一下。（我甚至之前一直在尝试用 Admin 用户名登录）

![image](https://user-images.githubusercontent.com/40235071/199017481-19b1b019-25e8-4da4-aadb-78394ba75504.png)

**Comment by TNTobsidian** [comment]
> 账号:admin
> 密码:admin

求助一下，面板使用默认帐号和密码也无法进入，提示密码错误。是nb脚手架安装的，通过安装文档中的命令更新到了最新版本。尝试通过网页注册账号后台还会报错（泪）
![image](https://user-images.githubusercontent.com/65720409/200111837-f666c615-41ad-4faa-88ad-3ebe5eb4cc43.png)

`11-05 16:56:25 [ERROR] uvicorn | Exception in ASGI application

Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.10/dist-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy_database/_abc_async_database.py", line 98, in asgi_dispatch
    async with self.__call__(scope=id(request.scope)):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy_database/database.py", line 348, in __aexit__
    await session.commit()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/ext/asyncio/session.py", line 583, in commit
    return await greenlet_spawn(self.sync_session.commit)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/_concurrency_py3k.py", line 115, in greenlet_spawn
    result = context.switch(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 827, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO auth_user (create_time, email, password, username, is_active, nickname, avatar, point) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2022-11-05 16:56:20.606596', None, SecretStr('**********'), 'admin', 1, None, None, 0.0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8) (Background on this error at: https://sqlalche.me/e/14/7s2a)

`

**Comment by KimigaiiWuyi** [comment]
> endingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked

这是注册的报错吧,登录的报错有吗
后台没有在执行`校验全部Cookies`之类的命令吧

**Comment by TNTobsidian** [comment]
> > endingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
> 
> 这是注册的报错吧,登录的报错有吗 后台没有在执行`校验全部Cookies`之类的命令吧

控制台没有报错，也没有执行检验cookies命令
```
11-06 09:52:43 [INFO] uvicorn | 84.17.45.179:25646 - "GET /auth/form/login?redirect=http://47.243.79.224:8080/genshinuid/ HTTP/1.1" 200
11-06 09:52:44 [INFO] uvicorn | 84.17.45.179:25654 - "GET /genshinuid HTTP/1.1" 307
11-06 09:52:45 [INFO] uvicorn | 84.17.45.179:25654 - "GET / HTTP/1.1" 307
11-06 09:52:46 [INFO] uvicorn | 84.17.45.179:25654 - "GET /auth/form/login?redirect=http://47.243.79.224:8080/genshinuid/ HTTP/1.1" 200
11-06 09:53:00 [INFO] uvicorn | 84.17.45.179:11786 - "POST /auth/form/login/api HTTP/1.1" 200

```

**Comment by TNTobsidian** [comment]
> > endingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
> 
> 这是注册的报错吧,登录的报错有吗 后台没有在执行`校验全部Cookies`之类的命令吧

在昨天开启网页控制台之后，执行和数据库修改的操作都会报错sqlite3.OperationalError database is locked
回滚目录下bak文件就恢复了，猜测和开启网页控制台有关

**Comment by KimigaiiWuyi** [comment]
> > > endingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
> > 
> > 
> > 这是注册的报错吧,登录的报错有吗 后台没有在执行`校验全部Cookies`之类的命令吧
> 
> 在昨天开启网页控制台之后，执行和数据库修改的操作都会报错sqlite3.OperationalError database is locked 回滚目录下bak文件就恢复了，猜测和开启网页控制台有关

`fastapi-amis-admin`的版本是?
重新开启网页控制台之后,重启bot,该问题能否复现

**Comment by TNTobsidian** [comment]
> > > > endingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
> > > 
> > > 
> > > 这是注册的报错吧,登录的报错有吗 后台没有在执行`校验全部Cookies`之类的命令吧
> > 
> > 
> > 在昨天开启网页控制台之后，执行和数据库修改的操作都会报错sqlite3.OperationalError database is locked 回滚目录下bak文件就恢复了，猜测和开启网页控制台有关
> 
> `fastapi-amis-admin`的版本是? 重新开启网页控制台之后,重启bot,该问题能否复现

fastapi_amis_admin版本是0.4.0
重新开启后，打开网页控制台，问题能够复现。
（在开启控制台后终端通过Ctrl+C关闭bot并nb run开启bot）
![IMG_1745](https://user-images.githubusercontent.com/65720409/200244000-8700e7a1-7e5b-4f07-ab4e-29150ef37e1c.jpeg)
终端报错
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE uiddata SET "UID"=?, "MYSID"=? WHERE uiddata."USERID" = ?]
[parameters: ('179968360_179968361_179968362', None, QQ号)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by KimigaiiWuyi** [comment]
> > > > > endingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
> > > > 
> > > > 
> > > > 这是注册的报错吧,登录的报错有吗 后台没有在执行`校验全部Cookies`之类的命令吧
> > > 
> > > 
> > > 在昨天开启网页控制台之后，执行和数据库修改的操作都会报错sqlite3.OperationalError database is locked 回滚目录下bak文件就恢复了，猜测和开启网页控制台有关
> > 
> > 
> > `fastapi-amis-admin`的版本是? 重新开启网页控制台之后,重启bot,该问题能否复现
> 
> fastapi_amis_admin版本是0.4.0 重新开启后，打开网页控制台，问题能够复现。 （在开启控制台后终端通过Ctrl+C关闭bot并nb run开启bot） ![IMG_1745](https://user-images.githubusercontent.com/65720409/200244000-8700e7a1-7e5b-4f07-ab4e-29150ef37e1c.jpeg) 终端报错
> 
> ```
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
> [SQL: UPDATE uiddata SET "UID"=?, "MYSID"=? WHERE uiddata."USERID" = ?]
> [parameters: ('179968360_179968361_179968362', None, QQ号)]
> (Background on this error at: https://sqlalche.me/e/14/e3q8)
> ```

我这边无法复现这个问题
database locked的原因一般是在写入数据库,但我不知道网页控制台和写入数据库有啥联系,难道是权限的问题

**Comment by TNTobsidian** [comment]
> > > > > > endingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
> > > > > 
> > > > > 
> > > > > 这是注册的报错吧,登录的报错有吗 后台没有在执行`校验全部Cookies`之类的命令吧
> > > > 
> > > > 
> > > > 在昨天开启网页控制台之后，执行和数据库修改的操作都会报错sqlite3.OperationalError database is locked 回滚目录下bak文件就恢复了，猜测和开启网页控制台有关
> > > 
> > > 
> > > `fastapi-amis-admin`的版本是? 重新开启网页控制台之后,重启bot,该问题能否复现
> > 
> > 
> > fastapi_amis_admin版本是0.4.0 重新开启后，打开网页控制台，问题能够复现。 （在开启控制台后终端通过Ctrl+C关闭bot并nb run开启bot） ![IMG_1745](https://user-images.githubusercontent.com/65720409/200244000-8700e7a1-7e5b-4f07-ab4e-29150ef37e1c.jpeg) 终端报错
> > ```
> > sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
> > [SQL: UPDATE uiddata SET "UID"=?, "MYSID"=? WHERE uiddata."USERID" = ?]
> > [parameters: ('179968360_179968361_179968362', None, QQ号)]
> > (Background on this error at: https://sqlalche.me/e/14/e3q8)
> > ```
> 
> 我这边无法复现这个问题 database locked的原因一般是在写入数据库,但我不知道网页控制台和写入数据库有啥联系,难道是权限的问题

😂 我查了一下ID DATA文件是644 root权限 应该也没有其他可疑的地方了，可能是和其他东西冲突了吧，谢谢您了
