### ISSUE TITLE
加载插件

### ISSUE THREAD

**Issue by glzat** [KimigaiiWuyi/GenshinUID#365]
11-01 10:15:33 [ERROR] nonebot | Failed to import "GenshinUID"
Traceback (most recent call last):
  File "c:\Users\Administrator\Downloads\bot\nb2\bot.py", line 37, in <module>
    nonebot.load_plugin('GenshinUID')
  File "C:\Python38\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Python38\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'GenshinUID'
请问下载插件后应将GenshinUID-nonebot2文件夹放在哪里？

**Comment by KimigaiiWuyi** [comment]
应当放入插件文件夹内，根据安装nb2时的选项，可能位于`scr`或者`plugins`下

**Comment by lgc2333** [comment]
> 应当放入插件文件夹内，根据安装nb2时的选项，可能位于`scr`或者`plugins`下

是`src/plugins`或者`<项目名>/plugins`文件夹

**Comment by lgc2333** [comment]
放到那个文件夹里之后 不需要往`bot.py`里加代码即可自动加载

**Comment by glzat** [comment]
> 放到那个文件夹里之后 不需要往里加代码即可自动加载`bot.py`

请问用nonebot.load_plugin还是nonebot.load_plugins

**Comment by KimigaiiWuyi** [comment]
> > 放到那个文件夹里之后 不需要往里加代码即可自动加载`bot.py`
> 
> 请问用nonebot.load_plugin还是nonebot.load_plugins

不需要任何加载代码

**Comment by glzat** [comment]
> 



> > > 放到那个文件夹里之后 不需要往里加代码即可自动加载`bot.py`
> > 
> > 
> > 请问用nonebot.load_plugin还是nonebot.load_plugins
> 
> 不需要任何加载代码

懂了，谢谢
