### ISSUE TITLE
查询角色面板出错

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#394]
```py
11-21 01:15:34 [SUCCESS] nonebot | OneBot V11 754024781 | [message.group.normal]: Message -1849063612 from 2324944124@[ 群:729885393] "查询钟离"
11-21 01:15:38 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.GenshinUID.GenshinUID.genshinuid_enka)
11-21 01:15:40 [INFO] genshinuid_enka | 开始执行[查询角色面板]
11-21 01:15:40 [INFO] genshinuid_enka | [查询角色面板]QQ: 2324944124
11-21 01:15:41 [INFO] genshinuid_enka | [查询角色面板]uid: 834809009
11-21 01:15:43 [SUCCESS] nonebot | OneBot V11 754024781 | [message_sent]: {'time': 1668964544, 'self_id': 754024781, 'post_type': 'message_sent', 'raw_message': "发生错误 'Enemy' object has no attribute 'ToxicResist'，请检查后台输出。", 'sub_type': 'normal', 'message': [{'type': 'text', 'data': {'text': "发生错误 'Enemy' object has no attribute 'ToxicResist'，请检查后台输出。"}}], 'message_id': -422660142, 'message_seq': 18801, 'anonymous': None, 'user_id': 754024781, 'font': 0, 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': 'Shigure 5th - Kira☆~', 'role': 'member', 'sex': 'unknown', 'title': '', 'user_id': 754024781}, 'group_id': 729885393, 'message_type': 'group'}
11-21 01:15:43 [ERROR] GenshinUID | 获取查询角色面板信息错误
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\utils\exception\handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\__init__.py", line 182, in send_char_info
    im = await draw_enka_img(raw_mes, uid, img)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\get_enka_img.py", line 108, in draw_enka_img
    im = await draw_char_img(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\draw_char_card.py", line 42, in draw_char_img
    res = await draw_char_card(char, charUrl)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\draw_char_card.py", line 47, in draw_char_card
    dmg_img, dmg_len = await draw_dmg_img(char)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\dmg_calc\dmg_calc.py", line 22, in draw_dmg_img
    dmg_data = await fight.get_dmg_dict(char.char_name)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\mono\Fight.py", line 72, in get_dmg_dict
    await self.get_new_fight_prop(char)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\mono\Fight.py", line 175, in get_new_fight_prop
    await self.enemy.update_resist(effect)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\.\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\mono\Enemy.py", line 39, in update_resist
    r = getattr(self, name)
AttributeError: 'Enemy' object has no attribute 'ToxicResist'
```

**Comment by KimigaiiWuyi** [comment]
更新

**Comment by lgc2333** [comment]
没用啊？？

**Comment by lgc2333** [comment]
今天看后台又多了一个
```py
11-21 17:03:30 [SUCCESS] nonebot | OneBot V11 754024781 | [message.group.normal]: Message 430052909 from 3057914700@[群:934067807] "查询展柜角色"
11-21 17:03:30 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.GenshinUID.GenshinUID.genshinuid_enka)
11-21 17:03:30 [INFO] genshinuid_enka | 开始执行[查询角色面板]
11-21 17:03:30 [INFO] genshinuid_enka | [查询角色面板]QQ: 3057914700
11-21 17:03:30 [INFO] genshinuid_enka | [查询角色面板]uid: 134685836
11-21 17:03:30 [SUCCESS] nonebot | OneBot V11 754024781 | [message_sent]: {'time': 1669021412, 'self_id': 754024781, 'post_type': 'message_sent', 'sub_type': 'normal', 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': 'Shigure 5th - Kira☆~', 'role': 'member', 'sex': 'unknown', 'title': '', 'user_id': 754024781}, 'anonymous': None, 'message_seq': 134138, 'message_type': 'group', 'font': 0, 'message_id': -1994585156, 'raw_message': '发生错误 tile cannot extend outside image，请检查后台输出。', 'message': [{'type': 'text', 'data': {'text': '发生错误 tile cannot extend outside image，请检查后台输出。'}}], 'user_id': 754024781, 'group_id': 934067807}
11-21 17:03:30 [ERROR] GenshinUID | 获取查询角色面板信息错误
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\bot.py", line 39, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\utils\exception\handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\__init__.py", line 182, in send_char_info
    im = await draw_enka_img(raw_mes, uid, img)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\get_enka_img.py", line 83, in draw_enka_img
    img = await draw_enka_card(uid=uid, char_list=char_list)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\utils\enka_api\enka_to_card.py", line 63, in draw_enka_card
    return await convert_img(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\utils\draw_image_tools\send_image_tool.py", line 24, in convert_img
    img.save(result_buffer, format='PNG', quality=80, subsampling=0)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\PIL\Image.py", line 2320, in save
    save_handler(self, fp, filename)
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\PIL\PngImagePlugin.py", line 1374, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\PIL\ImageFile.py", line 510, in _save
    encoder.setimage(im.im, b)
SystemError: tile cannot extend outside image
```

**Comment by KimigaiiWuyi** [comment]
> 今天看后台又多了一个
> 
> ```python
> 11-21 17:03:30 [SUCCESS] nonebot | OneBot V11 754024781 | [message.group.normal]: Message 430052909 from 3057914700@[群:934067807] "查询展柜角色"
> 11-21 17:03:30 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.GenshinUID.GenshinUID.genshinuid_enka)
> 11-21 17:03:30 [INFO] genshinuid_enka | 开始执行[查询角色面板]
> 11-21 17:03:30 [INFO] genshinuid_enka | [查询角色面板]QQ: 3057914700
> 11-21 17:03:30 [INFO] genshinuid_enka | [查询角色面板]uid: 134685836
> 11-21 17:03:30 [SUCCESS] nonebot | OneBot V11 754024781 | [message_sent]: {'time': 1669021412, 'self_id': 754024781, 'post_type': 'message_sent', 'sub_type': 'normal', 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': 'Shigure 5th - Kira☆~', 'role': 'member', 'sex': 'unknown', 'title': '', 'user_id': 754024781}, 'anonymous': None, 'message_seq': 134138, 'message_type': 'group', 'font': 0, 'message_id': -1994585156, 'raw_message': '发生错误 tile cannot extend outside image，请检查后台输出。', 'message': [{'type': 'text', 'data': {'text': '发生错误 tile cannot extend outside image，请检查后台输出。'}}], 'user_id': 754024781, 'group_id': 934067807}
> 11-21 17:03:30 [ERROR] GenshinUID | 获取查询角色面板信息错误
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\bot.py", line 39, in <module>
>     nonebot.run(app="__mp_main__:app")
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\__init__.py", line 273, in run
>     get_driver().run(*args, **kwargs)
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
>     uvicorn.run(
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\main.py", line 575, in run
>     server.run()
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\uvicorn\server.py", line 60, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "C:\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
>     self.run_forever()
>   File "C:\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
>     super().run_forever()
>   File "C:\Python310\lib\asyncio\base_events.py", line 600, in run_forever
>     self._run_once()
>   File "C:\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
>     handle._run()
>   File "C:\Python310\lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
>     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
>     await matcher.run(bot, event, state, stack, dependency_cache)
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
>     await self.simple_run(bot, event, state, stack, dependency_cache)
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
>     await handler(
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
>     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\utils\exception\handle_exception.py", line 32, in inner
>     await func(**kwargs)
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\__init__.py", line 182, in send_char_info
>     im = await draw_enka_img(raw_mes, uid, img)
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\genshinuid_enka\get_enka_img.py", line 83, in draw_enka_img
>     img = await draw_enka_card(uid=uid, char_list=char_list)
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\utils\enka_api\enka_to_card.py", line 63, in draw_enka_card
>     return await convert_img(
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\src\plugins\GenshinUID\GenshinUID\utils\draw_image_tools\send_image_tool.py", line 24, in convert_img
>     img.save(result_buffer, format='PNG', quality=80, subsampling=0)
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\PIL\Image.py", line 2320, in save
>     save_handler(self, fp, filename)
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\PIL\PngImagePlugin.py", line 1374, in _save
>     ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
>   File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2beta\env\lib\site-packages\PIL\ImageFile.py", line 510, in _save
>     encoder.setimage(im.im, b)
> SystemError: tile cannot extend outside image
> ```

这个应该是获取展柜信息的时候，没有刷新 所以是空的图片，回头优化一下

**Comment by lgc2333** [comment]
> > 没用啊？？
> 
> 这个bug前几天应该就修了

更新过了 没用

**Comment by lgc2333** [comment]
更新之后ok了 我本地git库有点问题
