### ISSUE TITLE
Nonebot2 安装错误

### ISSUE THREAD

**Issue by Binket** [KimigaiiWuyi/GenshinUID#395]
Python 3.8.10
pip 22.3.1

错误报告：https://paste.ubuntu.com/p/mwKmKzBfkd/

**Comment by KimigaiiWuyi** [comment]
未安装依赖`pillow`
报错信息
`ModuleNotFoundError: No module named 'PIL'`

**Comment by Binket** [comment]
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/72/db/0d1a944ba1517256e8b1a080a90297569d8662442631a6b05f8a1c584556/greenlet-0.2.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\2\pip-install-5_sir8p8\greenlet_8c0997571d3e4b3b95518166b4d34fc3\setup.py", line 3, in <module>
          import ez_setup
        File "C:\Users\Administrator\AppData\Local\Temp\2\pip-install-5_sir8p8\greenlet_8c0997571d3e4b3b95518166b4d34fc3\ez_setup\__init__.py", line 98
          except pkg_resources.VersionConflict, e:
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
