### ISSUE TITLE
hoshino启动时出现错误

### ISSUE THREAD

**Issue by Akilu1** [KimigaiiWuyi/GenshinUID#399]
![FHA~1L1~HJ6CWDVGSRR{1T0](https://user-images.githubusercontent.com/49243130/206186400-a7f9a36c-1866-4603-a1ce-9c04dda028b0.png)

均为添加了GenshenUID模块后出现的报错

[2022-12-07 20:57:49,243 nonebot] ERROR: 访问https://xkdata.jdsha.com/static/data/abyss_total.js失败！
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1080, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1110, in _create_connection_transport
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 974, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Hoshino\HoshinoBot\hoshino\modules\GenshinUID\GenshinUID\utils\xk_api\get_xk_data.py", line 46, in _xk_request
    req = await sess.request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host xkdata.jdsha.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')]

**Comment by KimigaiiWuyi** [comment]
进入[虚空数据库](https://akashadata.com/)
点击左上角，链接左边的小锁
链接是安全的 -> 证书有效 -> 导出证书
文件名随便写一个，后缀.crt
双击安装证书即可

**Comment by Akilu1** [comment]
虚空数据库中安装证书后仍然存在问题，通过下方https://akashadata.feixiaoqiu.com/static/data/abyss_total.js这里安装证书后问题解决，感谢！！~
