### ISSUE TITLE
[图片缺失]几乎加载不出来绝大部分图片

### ISSUE THREAD

**Issue by yhzcake** [KimigaiiWuyi/GenshinUID#406]
今天刚刚安装插件,强制刷新/查询/查询展柜角色/每日都报错 [Errno 2] No such file or directory
`12-17 22:25:14 [ERROR] GenshinUID | 获取查询角色面板信息错误
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\utils\exception\handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\genshinuid_enka\__init__.py", line 184, in send_char_info
    im = await draw_enka_img(raw_mes, uid, img)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\genshinuid_enka\get_enka_img.py", line 57, in draw_enka_img
    sc = await get_showcase(uid)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\genshinuid_enka\get_enka_img.py", line 118, in get_showcase
    img = await draw_enka_card(uid=uid, char_list=char_list)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\utils\enka_api\enka_to_card.py", line 98, in draw_enka_card
    await asyncio.gather(*tasks)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\utils\enka_api\enka_to_card.py", line 109, in draw_enka_char
    Image.open(CHAR_PATH / f'{char_id}.png')
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 3131, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\nonebot\\yhz_cake\\data\\GenshinUID\\resource\\chars\\10000065.png'`

<html>
<body>

GenshinUID Info
--
Windows | 3.10.7 | 3.1.0 | GPLv3

</body>
</html>

如果无法确认问题来源,我可以继续提供其他log

**Comment by KimigaiiWuyi** [comment]
启动时应该会自动下载资源文件，如果没能成功下载
可以使用命令`下载全部资源`
再反馈这个命令的错误log

**Comment by yhzcake** [comment]
`12-17 23:34:53 [ERROR] GenshinUID | 资源下载错误
Traceback (most recent call last):
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 500, in sock_connect
    return await fut
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 10060] Connect call failed ('61.183.41.124', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\utils\exception\handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\genshinuid_resource\__init__.py", line 48, in send_download_resource_msg
    im = await download_all_resource()
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\utils\download_resource\download_all_resource.py", line 7, in download_all_resource
    ret = await asyncio.gather(download_all_file_from_miniggicu())
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\utils\download_resource\download_from_miniggicu.py", line 75, in download_all_file_from_miniggicu
    base_data = await _get_url(file, sess)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\utils\download_resource\download_from_miniggicu.py", line 49, in _get_url
    req = await sess.get(url=url)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\yhz_cake\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host file.microgg.cn:443 ssl:default [Connect call failed ('61.183.41.124', 443)]
12-17 23:34:53 [INFO] nonebot | Matcher(type='message', module=GenshinUID.genshinuid_resource) running complete`

看上去是没连上资源服务器,是谁的网络问题?能手动下载吗?

**Comment by KimigaiiWuyi** [comment]
资源服务器暂时g了，可以先用这个
https://tmp.link/f/639de95791b4d

**Comment by KimigaiiWuyi** [comment]
下载服务器已恢复
