### ISSUE TITLE
远程反向websocket图片发送失败

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [KimigaiiWuyi/GenshinUID#427]
![UTUSTQM{90U_Z)PACBE9F8K](https://user-images.githubusercontent.com/86163024/212459699-1cfabe70-d89c-486c-a583-0efb5b8b34b8.png)
如图，无法发送图片
gocq报错如下
```
[2023-01-14 14:41:29] [WARNING]: 转换CQ码 ({"type": "image", "data": {"file": "file:///C:/Users/YuYue/Desktop/yuyue_bot/src/plugins/GenshinUID/GenshinUID/genshinuid_map/map_data/%E6%8F%90%E7%93%A6%E7%89%B9_%E5%8A%AB%E6%B3%A2%E8%8E%B2.jpg", "type": null, "cache": "true", "proxy": "true", "timeout": null}}) 到MiraiGo Element时出现错误: file not found 将忽略本 段CQ码.
[2023-01-14 14:41:29] [WARNING]: 群消息发送失败: 消息为空.
```
nonebot报错如下
```
01-14 14:41:29 [INFO] genshinuid_map | [查找资源点]正在执行...当前地图为提瓦特
01-14 14:41:29 [INFO] genshinuid_map | [查找资源点]参数: {'name': '劫波莲'}
01-14 14:41:29 [INFO] genshinuid_map | 本地已有提瓦特_劫波莲的资源点,直接发送...
01-14 14:41:29 [ERROR] GenshinUID | 发送查找资源点消息失败
Traceback (most recent call last):
  File "C:\Users\YuYue\Desktop\yuyue_bot\bot.py", line 40, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\YuYue\Desktop\yuyue_bot\src\plugins\GenshinUID\GenshinUID\utils\exception\handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "C:\Users\YuYue\Desktop\yuyue_bot\src\plugins\GenshinUID\GenshinUID\genshinuid_map\__init__.py", line 117, in send_find_map_msg
    await matcher.finish(MessageSegment.image(resource_temp_path))
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 476, in finish
    await cls.send(message, **kwargs)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 461, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 174, in send
    return await bot.send_msg(**params)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
    raise exception
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 132, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed
01-14 14:41:30 [INFO] nonebot | Matcher(type='message', module=src.plugins.GenshinUID.GenshinUID.genshinuid_map) running complete
```
当前目录也有正常生成的图片
![image](https://user-images.githubusercontent.com/86163024/212459789-e888c24e-f723-44fe-aadb-f998032fe2c5.png)

**Comment by YuYue-Amatsuki** [comment]
补充：gocq和nonebot的机器不是同一个，但在同一局域网下

**Comment by KimigaiiWuyi** [comment]
应该已修复，可以更新了
