### ISSUE TITLE
pip安装时失败

### ISSUE THREAD

**Issue by dixiatielu** [KimigaiiWuyi/GenshinUID#433]
### 环境
Ubuntu 22.04
Python 3.10.6
Nonebot2

## 错误
成功克隆仓库，但执行`pip3 install --editable ./GenshinUID-nonebot2`时报错：
```
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Obtaining file:///root/dxtl_bot/dxtlBot/GenshinUID-nonebot2
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///root/dxtl_bot/dxtlBot/GenshinUID-nonebot2 has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```
尝试去除`--editable`参数仍然报错：
```
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Processing ./GenshinUID-nonebot2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/usr/lib/python3/dist-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
        File "/usr/lib/python3/dist-packages/poetry/core/factory.py", line 43, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - Additional properties are not allowed ('group' was unexpected)
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
通过`pip3 install git+https://ghproxy.com/https://github.com/KimigaiiWuyi/GenshinUID.git@nonebot2-beta1#egg=GenshinUID`与上述报错相同

**Comment by KimigaiiWuyi** [comment]
建议使用第一种安装方式，即直接clone到plugins文件夹内

**Comment by MingxuanGame** [comment]
可能是你环境的 `poetry` 版本过低导致的
