### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by jugongchang** [KimigaiiWuyi/GenshinUID#494]

**Comment by jugongchang** [comment]
Traceback (most recent call last):
  File "core.py", line 118, in <module>
    main()
  File "core.py", line 62, in main
    from gsuid_core.webconsole.mount_app import site
  File "C:\Users\Administrator\Desktop\gsuid_core\gsuid_core\webconsole\__init__
.py", line 5, in <module>
    from gsuid_core.webconsole.mount_app import site
  File "C:\Users\Administrator\Desktop\gsuid_core\gsuid_core\webconsole\mount_ap
p.py", line 42, in <module>
    from gsuid_core.webconsole.create_config_panel import get_config_page
  File "C:\Users\Administrator\Desktop\gsuid_core\gsuid_core\webconsole\create_c
onfig_panel.py", line 1, in <module>
    from gsuid_core.plugins.GenshinUID.GenshinUID.genshinuid_config import (
  File "C:\Users\Administrator\Desktop\gsuid_core\gsuid_core\plugins\GenshinUID\
GenshinUID\genshinuid_config\__init__.py", line 9, in <module>
    from .draw_config_card import draw_config_img
  File "C:\Users\Administrator\Desktop\gsuid_core\gsuid_core\plugins\GenshinUID\
GenshinUID\genshinuid_config\draw_config_card.py", line 8, in <module>
    from .gs_config import gsconfig
  File "C:\Users\Administrator\Desktop\gsuid_core\gsuid_core\plugins\GenshinUID\
GenshinUID\genshinuid_config\gs_config.py", line 131, in <module>
    gsconfig = StringConfig()
  File "C:\Users\Administrator\Desktop\gsuid_core\gsuid_core\plugins\GenshinUID\
GenshinUID\genshinuid_config\gs_config.py", line 29, in __init__
    self.update_config()
  File "C:\Users\Administrator\Desktop\gsuid_core\gsuid_core\plugins\GenshinUID\
GenshinUID\genshinuid_config\gs_config.py", line 47, in update_config
    self.config: Dict[str, GSC] = msgjson.decode(
msgspec.ValidationError: Expected `object`, got `str` - at `$[...]`

C:\Users\Administrator\Desktop\gsuid_core\gsuid_core>pause
请按任意键继续. . .

**Comment by KimigaiiWuyi** [comment]
全新安装的吗 还是更新后报错

**Comment by jugongchang** [comment]
都不是，早上卡住了，我重启后就报错了，更新了代码没有解决

**Comment by KimigaiiWuyi** [comment]
> 都不是，早上卡住了，我重启后就报错了，更新了代码没有解决

删除gsuid_core/gsuid_core/config.json后重启core

**Comment by jugongchang** [comment]
解决了！谢谢大佬

**Comment by KimigaiiWuyi** [comment]
> > 都不是，早上卡住了，我重启后就报错了，更新了代码没有解决
> 
> 删除gsuid_core/gsuid_core/config.json后重启core



> 解决了！谢谢大佬

需要注意，该操作会重置`gs配置`中的选项，以及一部分自定义api设置，最好检查一下
