### ISSUE TITLE
强制刷新命令报错

### ISSUE THREAD

**Issue by yangzhan-1** [KimigaiiWuyi/GenshinUID#506]
[2023-04-18 13:43:42,512 genshinuid] INFO: Message 1238688308 triggered send_card_info.
[2023-04-18 13:43:45,712 genshinuid] ERROR: <class 'KeyError'> occured when send_card_info handling message 1238688308.
[2023-04-18 13:43:45,714 genshinuid] ERROR: 'UI_RelicIcon_15030_2'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot-master\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot-master\hoshino\modules\GenshinUID\GenshinUID\genshinuid_enka\__init__.py", line 173, in send_card_info
    im = await enka_to_card(uid)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot-master\hoshino\modules\GenshinUID\GenshinUID\utils\enka_api\enka_to_card.py", line 35, in enka_to_card
    char_data_list = await enka_to_dict(uid, enka_data)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot-master\hoshino\modules\GenshinUID\GenshinUID\utils\enka_api\enka_to_data.py", line 263, in enka_to_dict
    artifact_temp['aritifactName'] = icon2Name[
KeyError: 'UI_RelicIcon_15030_2'
[2023-04-18 13:43:45,730 nonebot] INFO: Message 1238688308 is ignored: Handled by Hoshino

**Comment by KimigaiiWuyi** [comment]
用`gs更新`或者手动命令行`git pull`更新，或者直接按文档更换新的v4分支

**Comment by KimigaiiWuyi** [comment]
用`gs更新`更新，或者直接按文档更换新的v4分支

**Comment by yangzhan-1** [comment]
还是不行，3.x版本更新没有解决问题，4.x更新提示有危险

**Comment by KimigaiiWuyi** [comment]
> 还是不行，3.x版本更新没有解决问题，4.x更新提示有危险

你没有更新成功，可能提示冲突了，可以截图命令行我看看解决方法
v4需要重新安装，导出v3数据在全新安装v4再导入v3数据，不能简单地替换源

**Comment by yangzhan-1** [comment]
我是两个机器人，一个3.x版本，一个4.x版本应该不存在没有更新成功的情况

**Comment by yangzhan-1** [comment]
![CC)E}3CSY@J REZBU}OR_8C](https://user-images.githubusercontent.com/67181805/232699810-3419ec5b-ea44-40ae-9d50-dce6bb2b7dec.jpg)

**Comment by KimigaiiWuyi** [comment]
给个uid

**Comment by KimigaiiWuyi** [comment]
![image](https://user-images.githubusercontent.com/55526518/232700326-647fec7b-958e-44e5-abf9-06fd075f3aa8.png)
按理来说不可能不存在这个键才对

**Comment by yangzhan-1** [comment]
很奇怪的是大部分人是可以用的，目前不可以用的只有小部分人，报错的uid:174293538

**Comment by KimigaiiWuyi** [comment]
> 很奇怪的是大部分人是可以用的，目前不可以用的只有小部分人，报错的uid:174293538

![image](https://user-images.githubusercontent.com/55526518/232700809-5ad12e99-b305-48b5-93bf-477d7f649ffd.png)
检查一下上面那个目录的文件，是否存在这个键，我这边是完全正常的，怀疑你没正确更新

**Comment by yangzhan-1** [comment]
我的3.x的昨天前还是正常的，我昨天只对游戏内展示角色进行了调整后就无法使用了，这个json我本地也是有的
![image](https://user-images.githubusercontent.com/67181805/232703077-875494fc-9d31-4438-81f0-56aeab77acb6.png)

**Comment by KimigaiiWuyi** [comment]
> 我的3.x的昨天前还是正常的，我昨天只对游戏内展示角色进行了调整后就无法使用了，这个json我本地也是有的 ![image](https://user-images.githubusercontent.com/67181805/232703077-875494fc-9d31-4438-81f0-56aeab77acb6.png)

重启bot和core看看

这个报错是由于新圣遗物的原因，如果没有正确更新插件，`metadata`加载的还是旧版本的，就无法识别新的圣遗物

`v4`可以尝试使用`gs全部更新`，确保返回提示无任何报错之后，用`gs重启`应用更新 检查是否仍有问题

**Comment by yangzhan-1** [comment]
重启后好了，感谢
