### ISSUE TITLE
接口问题？导入成功但不能用

### ISSUE THREAD

**Issue by 173322993** [KimigaiiWuyi/GenshinUID#539]
我真的会难过😔
[PyBot][23:22:03.934][INFO] [message] 触发 Matcher(type='message', module=GenshinUID)         [PyBot][23:22:03.937][INFO] [GenshinUID.client]Bot_ID: NoneBot2连接至[gsuid-core]: ws://localhost:8765/ws/NoneBot2...                        [PyBot][23:22:03.948][ERROR] [message]Running Matcher(type='message', module=GenshinUID) failed.                                             Traceback (most recent call last):               File "/root/TRSS_AllBot/Miao-Yunzai/plugins/py-plugin/main.py", line 17, in <module>            yunzai_nonebot.run()                         File "/root/TRSS_AllBot/Miao-Yunzai/plugins/py-plugin/yunzai_nonebot/__init__.py", line 31, in run                                             nonebot.run(*args, **kwargs)                 File "/root/TRSS_AllBot/home/.cache/pypoetry/
virtualenvs/py-plugin-FEAAEwa5-py3.10/lib/pytho
n3.10/site-packages/nonebot/__init__.py", line 309, in run                                        get_driver().run(*args, **kwargs)            File "/root/TRSS_AllBot/Miao-Yunzai/plugins/p
y-plugin/yunzai_nonebot/hijack/driver.py", line
 42, in run                                        loop.run_until_complete(self.serve())        File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()                           File "/usr/lib/python3.10/asyncio/base_events
.py", line 603, in run_forever                     self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()                                File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)                                              File "/root/TRSS_AllBot/Miao-Yunzai/plugins/py-plugin/yunzai_nonebot/hijack/message.py", line 10, in wrapper                                   return await func(*args, **kwargs)           File "/root/TRSS_AllBot/home/.cache/pypoetry/virtualenvs/py-plugin-FEAAEwa5-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher                              await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)                   > File "/root/TRSS_AllBot/home/.cache/pypoetry/virtualenvs/py-plugin-FEAAEwa5-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher                                await matcher.run(bot, event, state, stack, dependency_cache)                               File "/root/TRSS_AllBot/home/.cache/pypoetry/virtualenvs/py-plugin-FEAAEwa5-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/ma
tcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)                           File "/root/TRSS_AllBot/home/.cache/pypoetry/virtualenvs/py-plugin-FEAAEwa5-py3.10/lib/pytho
n3.10/site-packages/nonebot/internal/matcher/ma
tcher.py", line 728, in simple_run                 await handler(                               File "/root/TRSS_AllBot/home/.cache/pypoetry/virtualenvs/py-plugin-FEAAEwa5-py3.10/lib/pytho
n3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/TRSS_AllBot/Miao-Yunzai/plugins/py-plugin/plugins/GenshinUID/GenshinUID/__init__
.py", line 113, in get_all_message                 return await connect()
File "/root/TRSS_AllBot/Miao-Yunzai/plugins/py-plugin/plugins/GenshinUID/GenshinUID/__init__.py", line 404, in connect                         gsclient = await GsClient().async_connect()  File "/root/TRSS_AllBot/Miao-Yunzai/plugins/py-plugin/plugins/GenshinUID/GenshinUID/client.py", line 75, in async_connect
    cls.ws = await websockets.client.connect(
  File "/root/TRSS_AllBot/home/.cache/pypoetry/virtualenvs/py-plugin-FEAAEwa5-py3.10/lib/python3.10/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/root/TRSS_AllBot/home/.cache/pypoetry/virtualenvs/py-plugin-FEAAEwa5-py3.10/lib/python3.10/site-packages/websockets/legacy/client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1084, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 8765, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8765)

**Comment by KimigaiiWuyi** [comment]
如果需要通过docker或者其他隔离环境使用，需要把host改为`0.0.0.0`

**Comment by grinxxoo** [comment]
> 如果需要通过docker或者其他隔离环境使用，需要把host改为`0.0.0.0`
nonebot2插件自动安装的 怎么改ip和端口？在.env环境里添加吗

**Comment by KimigaiiWuyi** [comment]
core的config.json

**Comment by 173322993** [comment]
好像，没有core 要自己再装一个吗

**Comment by grinxxoo** [comment]
> core的config.json
> 

我的nobot目录结构里没有关于gscore的文件目录，启动nobot时提示gscore服务器连接失败如下:
05-14 17:14:56 [INFO] websockets | connection open
05-14 17:14:56 [INFO] GenshinUID | Bot_ID: NoneBot2连 接至[gsuid-core]: ws://127.0.0.1:9010/ws/NoneBot2...
05-14 17:14:56 [ERROR] GenshinUID | Core服务器连接失 ...请稍后使用[启动core]命令启动...

手动发送命令''启动core''时报错:
05-14 17:09:12 [SUCCESS] nonebot | OneBot V11 328997609 | [message.private.friend]: Message -1446582066 from 1522575015 '启动core'
05-14 17:09:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
05-14 17:09:12 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
05-14 17:09:12 [ERROR] nonebot | Running Matcher(type='message', module=GenshinUID) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/root/grer/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/root/grer/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/grer/.venv/lib/python3.9/site-packages/GenshinUID/__init__.py", line 390, in send_start_msg
    await matcher.send(await start())
  File "/root/grer/.venv/lib/python3.9/site-packages/GenshinUID/auto_install.py", line 38, in start
    subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/gsuid_core'

插件方式还需要自行下载源文件吗？小白一枚，望解答

**Comment by KimigaiiWuyi** [comment]
> > core的config.json
> 
> 我的nobot目录结构里没有关于gscore的文件目录，启动nobot时提示gscore服务器连接失败如下: 05-14 17:14:56 [INFO] websockets | connection open 05-14 17:14:56 [INFO] GenshinUID | Bot_ID: NoneBot2连 接至[gsuid-core]: ws://127.0.0.1:9010/ws/NoneBot2... 05-14 17:14:56 [ERROR] GenshinUID | Core服务器连接失 ...请稍后使用[启动core]命令启动...
> 
> 手动发送命令''启动core''时报错: 05-14 17:09:12 [SUCCESS] nonebot | OneBot V11 328997609 | [message.private.friend]: Message -1446582066 from 1522575015 '启动core' 05-14 17:09:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID) 05-14 17:09:12 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete 05-14 17:09:12 [ERROR] nonebot | Running Matcher(type='message', module=GenshinUID) failed. Traceback (most recent call last): File "", line 17, in File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/**init**.py", line 309, in run get_driver().run(*args, **kwargs) File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 198, in run uvicorn.run( File "/root/grer/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 568, in run server.run() File "/root/grer/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run return asyncio.run(self.serve(sockets=sockets)) File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/message.py", line 141, in _check_matcher await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> 
> > File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/message.py", line 187, in _run_matcher
> > await matcher.run(bot, event, state, stack, dependency_cache)
> > File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
> > await self.simple_run(bot, event, state, stack, dependency_cache)
> > File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
> > await handler(
> > File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/dependencies/**init**.py", line 108, in **call**
> > return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > File "/root/grer/.venv/lib/python3.9/site-packages/GenshinUID/**init**.py", line 390, in send_start_msg
> > await matcher.send(await start())
> > File "/root/grer/.venv/lib/python3.9/site-packages/GenshinUID/auto_install.py", line 38, in start
> > subprocess.Popen(
> > File "/usr/lib/python3.9/subprocess.py", line 951, in **init**
> > self._execute_child(args, executable, preexec_fn, close_fds,
> > File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
> > raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: '/root/gsuid_core'
> 
> 插件方式还需要自行下载源文件吗？小白一枚，望解答

路径有问题，你还是自己去`gsuid_core`文件夹内手动启动，`poetry run python core.py`

**Comment by 173322993** [comment]
> core的config.json

好像没有core这个文件，怎么办

**Comment by grinxxoo** [comment]
> > > core的config.json
> > 
> > 我的nobot目录结构里没有关于gscore的文件目录，启动nobot时提示gscore服务器连接失败如下: 05-14 17:14:56 [INFO] websockets | connection open 05-14 17:14:56 [INFO] GenshinUID | Bot_ID: NoneBot2连 接至[gsuid-core]: ws://127.0.0.1:9010/ws/NoneBot2... 05-14 17:14:56 [ERROR] GenshinUID | Core服务器连接失 ...请稍后使用[启动core]命令启动...
> > 
> > 手动发送命令''启动core''时报错: 05-14 17:09:12 [SUCCESS] nonebot | OneBot V11 328997609 | [message.private.friend]: Message -1446582066 from 1522575015 '启动core' 05-14 17:09:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID) 05-14 17:09:12 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete 05-14 17:09:12 [ERROR] nonebot | Running Matcher(type='message', module=GenshinUID) failed. Traceback (most recent call last): File "", line 17, in File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/**init**.py", line 309, in run get_driver().run(*args, **kwargs) File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 198, in run uvicorn.run( File "/root/grer/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 568, in run server.run() File "/root/grer/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run return asyncio.run(self.serve(sockets=sockets)) File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/message.py", line 141, in _check_matcher await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> > 
> > > File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/message.py", line 187, in _run_matcher
> > > await matcher.run(bot, event, state, stack, dependency_cache)
> > > File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
> > > await self.simple_run(bot, event, state, stack, dependency_cache)
> > > File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
> > > await handler(
> > > File "/root/grer/.venv/lib/python3.9/site-packages/nonebot/dependencies/**init**.py", line 108, in **call**
> > > return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > > File "/root/grer/.venv/lib/python3.9/site-packages/GenshinUID/**init**.py", line 390, in send_start_msg
> > > await matcher.send(await start())
> > > File "/root/grer/.venv/lib/python3.9/site-packages/GenshinUID/auto_install.py", line 38, in start
> > > subprocess.Popen(
> > > File "/usr/lib/python3.9/subprocess.py", line 951, in **init**
> > > self._execute_child(args, executable, preexec_fn, close_fds,
> > > File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
> > > raise child_exception_type(errno_num, err_msg, err_filename)
> > > FileNotFoundError: [Errno 2] No such file or directory: '/root/gsuid_core'
> > 
> > 插件方式还需要自行下载源文件吗？小白一枚，望解答
> 
> 路径有问题，你还是自己去`gsuid_core`文件夹内手动启动，`poetry run python core.py`

手动安装运行又有新的报错了惹:

05-14 18:09:57 [ERROR] uvicorn.lifespan.on | Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 228, in _handle_exception
    raise error
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn    value = await result
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/aiosqlite/cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/aiosqlite/cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
sqlite3.OperationalError: table auth_user_roles already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/root/gsuid_core/gsuid_core/core.py", line 64, in startup_event
    await start_check()
  File "/root/gsuid_core/gsuid_core/webconsole/__init__.py", line 20, in start_check
    await site.auth.db.async_run_sync(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy_database/database.py", line 196, in run_sync
    return await conn.run_sync(fn, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 548, in run_sync
    return await greenlet_spawn(fn, conn, *arg, **kw)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn    result = context.throw(*sys.exc_info())
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4917, in create_all
    bind._run_ddl_visitor(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2211, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 851, in visit_metadata
    self.traverse_single(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 895, in visit_table
    self.connection.execute(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 280, in execute
    return self._execute_20(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1472, in _execute_ddl
    ret = self._execute_context(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 228, in _handle_exception
    raise error
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn    value = await result
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/aiosqlite/cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/aiosqlite/cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-hawraRrE-py3.9/lib/python3.9/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table auth_user_roles already exists
[SQL:
CREATE TABLE auth_user_roles (
        user_id INTEGER NOT NULL,
        role_id INTEGER NOT NULL,
        PRIMARY KEY (user_id, role_id),
        FOREIGN KEY(user_id) REFERENCES auth_user (id) ON DELETE CASCADE,
        FOREIGN KEY(role_id) REFERENCES auth_role (id) ON DELETE CASCADE
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

05-14 18:09:57 [ERROR] uvicorn.lifespan.on | Application startup failed. Exiting.
root@localhost:~/gsuid_core/gsuid_core#

**Comment by KimigaiiWuyi** [comment]
看样子是数据库问题，可以尝试删除数据库后再试
v3数据库和v4不通用
可以通过文档的 导入导出 一节中找到如何转移数据
