### ISSUE TITLE
无法导入GenshinUID插件

### ISSUE THREAD

**Issue by ab-Royo** [KimigaiiWuyi/GenshinUID#553]
之前GenshinUID和其他插件都在一个机器人中，以前一直运行正常，今天重启之后GenshinUID插件就无法导入，服务器是有安装Git的。
更换了一个新的机器人，只安装了GenshinUID插件，仍然报错，报错如下。
在.venv\lib\site-packages\git\ _ _init_ _.py文件中添加`os.environ["GIT_PYTHON_REFRESH"] = "quiet"`后可以正常导入插件，但是响应指令时仍然报错

```
C:\Users\Administrator\Desktop\QBot\mihoyo02>nb run
使用 Python: C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\Scripts\python.exe
05-30 13:22:43 [SUCCESS] nonebot | NoneBot is initializing...
05-30 13:22:43 [INFO] nonebot | Current Env: prod
05-30 13:22:43 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
05-30 13:22:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
05-30 13:22:45 [ERROR] nonebot | Failed to import "GenshinUID"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\git\cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\GenshinUID\__init__.py", line 23, in <module>
    from .auto_install import start, install  # noqa:E402
  File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\GenshinUID\auto_install.py", line 4, in <module>
    from git.repo import Repo
  File "C:\Users\Administrator\Desktop\QBot\mihoyo02\.venv\lib\site-packages\git\__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

05-30 13:22:45 [SUCCESS] nonebot | Running NoneBot...
```

**Comment by KimigaiiWuyi** [comment]
需要装git
