### ISSUE TITLE
启动后报错，整个资源文件夹都没有自动去下载

### ISSUE THREAD

**Issue by yangzhan-1** [KimigaiiWuyi/GenshinUID#559]
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<SQLA._create_all() done, defined at C:\Users\Administrator\Desktop\v4\gsuid_core\gsuid_core\utils\database\dal.py:35> exception=OperationalError('(sqlite3.OperationalError) table gsbind already exists')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 228, in _handle_exception
    raise error
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\aiosqlite\cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\aiosqlite\cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\aiosqlite\core.py", line 133, in _execute
    return await future
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\aiosqlite\core.py", line 106, in run
    result = function()
sqlite3.OperationalError: table gsbind already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\v4\gsuid_core\gsuid_core\utils\database\dal.py", line 37, in _create_all
    await conn.run_sync(SQLModel.metadata.create_all)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 548, in run_sync
    return await greenlet_spawn(fn, conn, *arg, **kw)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 126, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\sql\schema.py", line 4917, in create_all
    bind._run_ddl_visitor(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\engine\base.py", line 2211, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\sql\visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\sql\ddl.py", line 851, in visit_metadata
    self.traverse_single(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\sql\visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\sql\ddl.py", line 895, in visit_table
    self.connection.execute(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\future\engine.py", line 280, in execute
    return self._execute_20(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\sql\ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\engine\base.py", line 1472, in _execute_ddl
    ret = self._execute_context(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 228, in _handle_exception
    raise error
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\aiosqlite\cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\aiosqlite\cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\aiosqlite\core.py", line 133, in _execute
    return await future
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-jL1TTV1a-py3.8\lib\site-packages\aiosqlite\core.py", line 106, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table gsbind already exists
[SQL:
CREATE TABLE gsbind (
        id INTEGER NOT NULL,
        bot_id VARCHAR NOT NULL,
        user_id VARCHAR NOT NULL,
        uid VARCHAR,
        sr_uid VARCHAR,
        mys_id VARCHAR,
        PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by KimigaiiWuyi** [comment]
更新core到最新不应该有这种错误才对

**Comment by yangzhan-1** [comment]
我是今天刚刚下的最新的core

**Comment by yangzhan-1** [comment]
目前只能去下载资源包手动替换

**Comment by KimigaiiWuyi** [comment]
这个错误也并不影响资源包来着，是否会导致无法启动core呢？

**Comment by yangzhan-1** [comment]
其他都正常使用，就是没有去下载资源导致返回值的图片全是none

**Comment by yangzhan-1** [comment]
查询一些数据类的指令无法使用（查询角色，深渊概览等）

**Comment by KimigaiiWuyi** [comment]
> 查询一些数据类的指令无法使用（查询角色，深渊概览等）

看看后台报错

**Comment by yangzhan-1** [comment]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/5ee1b249-f54a-45a3-89ed-7baac65ae309)

**Comment by yangzhan-1** [comment]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/b3aa6300-cab8-4ef0-baed-04164466c682)

**Comment by KimigaiiWuyi** [comment]
> 查询一些数据类的指令无法使用（查询角色，深渊概览等）

这些都是由于资源包没有自动下载造成的吧

**Comment by yangzhan-1** [comment]
对

**Comment by yangzhan-1** [comment]
找不到资源就返回none了

**Comment by yangzhan-1** [comment]
我去下载了资源包这几个指令也没办法正常使用

**Comment by KimigaiiWuyi** [comment]
> 对

打开`/gsuid_core/gsuid_core/utils/database/dal.py#L40`附近的代码，截图我看看，理论上不应该出现报错

**Comment by KimigaiiWuyi** [comment]
> 我是今天刚刚下的最新的core

可能仍然启动了旧版本的core

**Comment by yangzhan-1** [comment]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/502a7b82-80be-467d-827f-6c6b17acfea1)

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/67181805/244998366-502a7b82-80be-467d-827f-6c6b17acfea1.png)

看上去是没什么问题，你确定启动的是这个地方的core么？
手动启动看看

**Comment by yangzhan-1** [comment]
就是手动启动的

**Comment by KimigaiiWuyi** [comment]
这就怪了，那你可以选择注释掉38行，看看启动有无变化

**Comment by yangzhan-1** [comment]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/2ca3f3dd-1624-48e9-a155-004bfa6dced1)

**Comment by yangzhan-1** [comment]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/5dab8141-b3be-4610-a389-5c37ea40d784)

**Comment by KimigaiiWuyi** [comment]
下载服务器g了，等我联系一下灰灰

**Comment by yangzhan-1** [comment]
好家伙这个原因吗

**Comment by yangzhan-1** [comment]
我想到了，但没完全想到

**Comment by yangzhan-1** [comment]
启动好和我说一下我重新启动看看能不能拉，我现在手动下载的资源包不会影响吧

**Comment by KimigaiiWuyi** [comment]
> 启动好和我说一下我重新启动看看能不能拉，我现在手动下载的资源包不会影响吧

不会影响，放心

**Comment by yangzhan-1** [comment]
还没重启好吗

**Comment by yangzhan-1** [comment]
有大概的修复时间吗
