### ISSUE TITLE
绑定信息报错、资源下载失败

### ISSUE THREAD

**Issue by Pull256** [KimigaiiWuyi/GenshinUID#575]
**感谢作者的机器人，这个是很难得的支持qq频道的机器人了，但是我在使用的时候也发现了一些问题，比如**

### 1、绑定信息报错
输入绑定信息后，机器人无回复，查询后台日志发现错误
`Task exception was never retrieved
future: <Task finished name='Task-2245' coro=<send_bind_card() done, defined at /root/qqbot/gsuid_core/gsuid_core/plugins/core_command/core_user/__init__.py:14> exception=AttributeError("'NoneType' object has no attribute 'coin_push'")>
Traceback (most recent call last):
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/core_command/core_user/__init__.py", line 17, in send_bind_card
    im = await get_user_card(ev.bot_id, ev.user_id)
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/core_command/core_user/draw_user_card.py", line 106, in get_user_card
    getattr(user_push_data, f'{mode}_push'),
AttributeError: 'NoneType' object has no attribute 'coin_push'`

### 2、资源下载失败
机器人开启时，下载资源失败，具体错误为
`  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_start/__init__.py", line 24, in all_start
    await startup()
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_resource/__init__.py", line 20, in startup
    logger.info(f'[资源文件下载] {await download_all_resource()}')
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_all_resource.py", line 7, in download_all_resource
    ret = await asyncio.gather(download_all_file_from_miniggicu())
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_from_miniggicu.py", line 79, in download_all_file_from_miniggicu
    base_data = await _get_url(file, sess)
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_from_miniggicu.py", line 52, in _get_url
    req = await sess.get(url=url)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_start/__init__.py", line 24, in all_start
    await startup()
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_resource/__init__.py", line 20, in startup
    logger.info(f'[资源文件下载] {await download_all_resource()}')
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_all_resource.py", line 7, in download_all_resource
    ret = await asyncio.gather(download_all_file_from_miniggicu())
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_from_miniggicu.py", line 79, in download_all_file_from_miniggicu
    base_data = await _get_url(file, sess)
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_from_miniggicu.py", line 52, in _get_url
    req = await sess.get(url=url)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
None 
None 
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_start/__init__.py", line 24, in all_start
    await startup()
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_start/__init__.py", line 24, in all_start
    await startup()
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_resource/__init__.py", line 20, in startup
    logger.info(f'[资源文件下载] {await download_all_resource()}')
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_all_resource.py", line 7, in download_all_resource
    ret = await asyncio.gather(download_all_file_from_miniggicu())
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_from_miniggicu.py", line 79, in download_all_file_from_miniggicu
    base_data = await _get_url(file, sess)
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_resource/__init__.py", line 20, in startup
    logger.info(f'[资源文件下载] {await download_all_resource()}')
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_all_resource.py", line 7, in download_all_resource
    ret = await asyncio.gather(download_all_file_from_miniggicu())
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_from_miniggicu.py", line 52, in _get_url
    req = await sess.get(url=url)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_from_miniggicu.py", line 79, in download_all_file_from_miniggicu
    base_data = await _get_url(file, sess)
  File "/root/qqbot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/utils/resource/download_from_miniggicu.py", line 52, in _get_url
    req = await sess.get(url=url)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-sLDGaYn0-py3.8/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
`

**Comment by KimigaiiWuyi** [comment]
第一点是由于必须要先`绑定uid`和`扫码绑定`添加CK才可以；
第二点是由于资源服务器暂时出问题，建议手动下载资源包，具体地址在文档里也有https://www.123pan.com/s/St4DVv-jwejH.html提取码:Wuyi

**Comment by KimigaiiWuyi** [comment]
第一点还需要更新gsuid-core后重启bot
