### ISSUE TITLE
武器介绍报错

### ISSUE THREAD

**Issue by SeeWhyRan** [KimigaiiWuyi/GenshinUID#592]
10-14 11:58:39 [INFO] gsuid_core.handler | [Command] command=武器介绍, text= 雾切 
Task exception was never retrieved
future: <Task finished name='Task-307' coro=<send_weapon() done, defined at /home/ubuntu/nonebots/gsuid_core/gsuid_core/sv.py:30> exception=ValueError('bad transparency mask')>
Traceback (most recent call last):
  File "/home/ubuntu/nonebots/gsuid_core/gsuid_core/sv.py", line 33, in wrapper
    result = await func(bot, event)
  File "/home/ubuntu/nonebots/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_wikitext/__init__.py", line 66, in send_weapon
    im = await get_weapons_wiki_img(name)
  File "/home/ubuntu/nonebots/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_wikitext/get_weapons_pic.py", line 56, in get_weapons_wiki_img
    img = await draw_weapons_wiki_img(data, stats)
  File "/home/ubuntu/nonebots/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_wikitext/get_weapons_pic.py", line 206, in draw_weapons_wiki_img
    wiki_cost_bg.paste(cost_pic, (67 + t, 46), cost_pic)
  File "/home/ubuntu/myenv/venv/lib/python3.10/site-packages/PIL/Image.py", line 1713, in paste
    self.im.paste(im, box, mask.im)
ValueError: bad transparency mask
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/127853582/97e1d00e-f322-4a2c-bdf5-f5cee616ff31)

**Comment by KimigaiiWuyi** [comment]
更新后检查是否已修复
