### ISSUE TITLE
原神公告命令不可用 AttributeError: 'FreeTypeFont' object has no attribute 'getsize' & raise Exception('公告ID不正确')

### ISSUE THREAD

**Issue by Ghost-chu** [KimigaiiWuyi/GenshinUID#604]
```
11-11 16:35:03 [INFO] gsuid_core.handler | [Command] command=原神公告, text=
Task exception was never retrieved
future: <Task finished name='Task-2051' coro=<ann_() done, defined at C:\Users\Ghost_chu\Desktop\BRBot\gsuid_core\gsuid_core\sv.py:30> exception=AttributeError("'FreeTypeFont' object has no attribute 'getsize'")>
Traceback (most recent call last):
  File "C:\Users\Ghost_chu\Desktop\BRBot\gsuid_core\gsuid_core\sv.py", line 33, in wrapper
    result = await func(bot, event)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ghost_chu\Desktop\BRBot\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_ann\__init__.py", line 28, in ann_
    img = await ann_list_card()
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ghost_chu\Desktop\BRBot\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_ann\ann_card.py", line 52, in ann_list_card
    draw_text_by_line(
  File "C:\Users\Ghost_chu\Desktop\BRBot\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\utils\image\image_tools.py", line 67, in draw_text_by_line
    _, h = font.getsize('X')  # type: ignore
           ^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
```

**Comment by KimigaiiWuyi** [comment]
尝试更新后查看

**Comment by Ghost-chu** [comment]
> Owner

仍然存在问题，未修复彻底，提示ID不存在但实际上是存在的

```
11-12 01:14:30 [INFO] gsuid_core.handler | [Trigger] 消息 「原神公告#3927」 触发 「command」 类型触发器, 关键词: 「原神 公告」
11-12 01:14:30 [INFO] gsuid_core.handler | [Command] command=原神公告, text=#3927
Task exception was never retrieved
future: <Task finished name='Task-375' coro=<ann_() done, defined at C:\Users\Ghost_chu\Desktop\BRBot\gsuid_core\gsuid_core\sv.py:30> exception=Exception('公告ID不正确')>
Traceback (most recent call last):
  File "C:\Users\Ghost_chu\Desktop\BRBot\gsuid_core\gsuid_core\sv.py", line 33, in wrapper
    result = await func(bot, event)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ghost_chu\Desktop\BRBot\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_ann\__init__.py", line 33, in ann_
    raise Exception('公告ID不正确')
Exception: 公告ID不正确
11-12 01:15:19 [INFO] gsuid_core.handler | [Raw] raw_text=原神公告#20162, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=dodo, bot_self_id=66077028, msg_id=511348234590347264, user_type=group, group_id=2050385, user_id=3898474, user_pm=6, content=[Message(type='text', data='原神公告#20162')],
11-12 01:15:19 [INFO] gsuid_core.handler | [Trigger] 消息 「原神公告#20162」 触发 「command」 类型触发器, 关键词: 「原神公告」
11-12 01:15:19 [INFO] gsuid_core.handler | [Command] command=原神公告, text=#20162
Task exception was never retrieved
future: <Task finished name='Task-534' coro=<ann_() done, defined at C:\Users\Ghost_chu\Desktop\BRBot\gsuid_core\gsuid_core\sv.py:30> exception=Exception('公告ID不正确')>
Traceback (most recent call last):
  File "C:\Users\Ghost_chu\Desktop\BRBot\gsuid_core\gsuid_core\sv.py", line 33, in wrapper
    result = await func(bot, event)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ghost_chu\Desktop\BRBot\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_ann\__init__.py", line 33, in ann_
    raise Exception('公告ID不正确')
Exception: 公告ID不正确
```

![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/30802565/081b4cfc-05bf-43ef-93bc-fd975d7b0357)

**Comment by KimigaiiWuyi** [comment]
更新后检查是否已修复
