### ISSUE TITLE
guid + nb2 - 使用DoDo适配器时，图片消息似乎会多发送一条空消息

### ISSUE THREAD

**Issue by Ghost-chu** [KimigaiiWuyi/GenshinUID#609]
guid 日志:

```
11-12 22:35:47 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_update | 检查遗留信息...
11-12 22:35:51 [INFO] gsuid_core.handler | [Raw] raw_text=查询温迪, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=dodo, bot_self_id=66077028, msg_id=511670491824537600, user_type=group, group_id=2050385, user_id=3898474, user_pm=6, content=[Message(type='text', data='查询温迪')],
11-12 22:35:51 [INFO] gsuid_core.handler | [Trigger] 消息 「查询温迪」 触发 「command」 类型触发器, 关键词: 「查询」
11-12 22:35:51 [INFO] gsuid_core.handler | [Command] command=查询, text=温迪
11-12 22:35:51 [INFO] gsuid_core.handler | [Trigger] 消息 「查询温迪」 触发 「prefix」 类型触发器, 关键词: 「查询」
11-12 22:35:51 [INFO] gsuid_core.handler | [Command] command=查询, text=温迪
11-12 22:35:55 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_enka.get_enka_img | [查询角色] 绘图完成,等待发送...
11-12 22:35:55 [INFO] gsuid_core.bot | [发送消息to] dodo - group - 2050385

```

nb2 日志：

```
11-12 22:35:47 [INFO] GenshinUID | Bot_ID: NoneBot2连接至[gsuid-core]: ws://localhost:8765/ws/NoneBot2...
11-12 22:35:47 [SUCCESS] GenshinUID | 与[gsuid-core]成功连接! Bot_ID: NoneBot2
11-12 22:35:51 [SUCCESS] nonebot | DoDo 66077028 | [ChannelMessageEvent]: {'event_id': '2be3cd6d021248d5bfe84ac135e837f7', 'event_type': <EventType.MESSAGE: '2001'>, 'timestamp': datetime.datetime(2023, 11, 12, 14, 35, 51, 629000, tzinfo=datetime.timezone.utc), 'dodo_source_id': '3898474', 'island_source_id': '242320', 'personal': {'nick_name': 'Ghost_chu', 'avatar_url': 'https://img.imdodo.com/dodo/ba61ce6ca6a4a7f90713738b79f387dd.jpg', 'sex': <Sex.PRIVACY: -1>}, 'message_id': '511670491824537600', 'message_type': <MessageType.TEXT: 1>, 'message_body': {'content': '查询温迪'}, 'to_me': False, 'member': {'nick_name': 'Ghost_chu', 'join_time': datetime.datetime(2023, 10, 3, 22, 58, 26)}, 'channel_id': '2050385', 'reference': None, '_message': [TextSegment(type='text', data={'text': '查询温迪'})], '_origin_message': [TextSegment(type='text', data={'text': '查询温迪'})]}
11-12 22:35:51 [DEBUG] nonebot | Checking for matchers in priority 1...
11-12 22:35:51 [DEBUG] nonebot | Checking for matchers in priority 999...
11-12 22:35:51 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID, lineno=26)
11-12 22:35:51 [DEBUG] nonebot | Running Matcher(type='message', module=GenshinUID, lineno=26)
11-12 22:35:51 [DEBUG] nonebot | Running handler Dependent(call=get_all_message)
11-12 22:35:51 [DEBUG] GenshinUID | [ChannelMessageEvent]: {'event_id': '2be3cd6d021248d5bfe84ac135e837f7', 'event_type': <EventType.MESSAGE: '2001'>, 'timestamp': datetime.datetime(2023, 11, 12, 14, 35, 51, 629000, tzinfo=datetime.timezone.utc), 'dodo_source_id': '3898474', 'island_source_id': '242320', 'personal': {'nick_name': 'Ghost_chu', 'avatar_url': 'https://img.imdodo.com/dodo/ba61ce6ca6a4a7f90713738b79f387dd.jpg', 'sex': <Sex.PRIVACY: -1>}, 'message_id': '511670491824537600', 'message_type': <MessageType.TEXT: 1>, 'message_body': {'content': '查询温迪'}, 'to_me': False, 'member': {'nick_name': 'Ghost_chu', 'join_time': datetime.datetime(2023, 10, 3, 22, 58, 26)}, 'channel_id': '2050385', 'reference': None, '_message': [TextSegment(type='text', data={'text': '查询温迪'})], '_origin_message': [TextSegment(type='text', data={'text': '查询温迪'})]}
11-12 22:35:51 [INFO] GenshinUID | 【发送】[gsuid-core]: dodo
11-12 22:35:51 [INFO] nonebot | Matcher(type='message', module=GenshinUID, lineno=26) running complete
11-12 22:35:51 [DEBUG] nonebot | Stop event propagation
11-12 22:35:51 [DEBUG] nonebot | Checking for matchers completed
11-12 22:35:52 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
11-12 22:35:52 [INFO] GenshinUID | 开始执行[查询角色面板]
11-12 22:35:52 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
11-12 22:35:52 [INFO] GenshinUID | [查询角色面板]uid: 175594105
11-12 22:35:55 [INFO] GenshinUID | 【接收】[gsuid-core]: dodo - group - 2050385
11-12 22:35:55 [DEBUG] nonebot | DoDo | Bot 66077028 calling API set_resouce_picture_upload
11-12 22:36:01 [DEBUG] nonebot | DoDo | Bot 66077028 calling API set_channel_message_send
11-12 22:36:07 [DEBUG] nonebot | DoDo | Bot 66077028 calling API set_channel_message_send
11-12 22:36:11 [WARNING] apscheduler | Run time of job "repeat_connect (trigger: cron[second='*/10'], next run at: 2023-11-12 22:36:20 CST)" was missed by 0:00:01.591506
11-12 22:36:11 [ERROR] GenshinUID | <ActionFailed: 10002, 请求参数不允许为空>
Traceback (most recent call last):
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\bot.py", line 17, in <module>
    nonebot.run()
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\drivers\none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\Ghost_chu\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 274, in recv_msg
    await dodo_send(
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 736, in dodo_send
    await _send(content, image)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 724, in _send
    await __send(message)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\GenshinUID\client.py", line 692, in __send
    await bot.send_to_channel(
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\bot.py", line 140, in send_to_channel
    await self.set_channel_message_send(
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 123, in call_api
    raise exception
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\adapter.py", line 175, in _call_api
    return await api_handler(bot, **data)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\utils.py", line 63, in __call__
    return await self.func(inst, *args, **kwds)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\bot.py", line 435, in set_channel_message_send
    return parse_obj_as(MessageReturn, await self._request(request))
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\bot.py", line 227, in _request
    return self._handle_response(response)
  File "C:\Users\Ghost_chu\Desktop\BRBot\br-yuanshen-bot\.venv\Lib\site-packages\nonebot\adapters\dodo\bot.py", line 212, in _handle_response
    raise ActionFailed(result.status, result.message)
nonebot.adapters.dodo.exception.ActionFailed: <ActionFailed: 10002, 请求参数不允许为空>
```

对 GenshinUID nb2 插件发送信息的代码段前插入调试打印段：

![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/30802565/42ba2ae5-0d01-4e31-9a69-25da7958de01)

于此有关的问题 https://github.com/nonebot/adapter-dodo/issues/2

**Comment by CMHopeSunshine** [comment]
看了下相关代码，确实是的，在 `if image`分支调用`await __send`之后重新构造了条空消息再次发送，~~是不是忘了return~~
```python
async def _send(content: Optional[str], image: Optional[str]):
        message = Message()
        if image:
            img_bytes = base64.b64decode(image.replace('base64://', ''))
            image_return = await bot.set_resouce_picture_upload(file=img_bytes)
            message.append(
                MessageSegment.picture(
                    image_return.url, image_return.width, image_return.height
                )
            )
            await __send(message)
            message = Message()

        if content:
            message.append(MessageSegment.text(content))
        if markdown:
            message.append(MessageSegment.text(markdown))
        if at_list and target_type == 'group':
            for at in at_list:
                message.append(MessageSegment.at_user(at))

        if buttons:
            logger.warning('[gscore] DoDo暂不支持发送buttons消息')

        await __send(message)
```
