### ISSUE TITLE
mys设备登录后，无法执行查询

### ISSUE THREAD

**Issue by YingLing3** [KimigaiiWuyi/GenshinUID#610]
Task exception was never retrieved
future: <Task finished name='Task-7394' coro=<send_role_info() done, defined at /home/bot/gsuid_core/gsuid_core/sv.py:30> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/bot/gsuid_core/gsuid_core/sv.py", line 33, in wrapper
    result = await func(bot, event)
  File "/home/bot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_roleinfo/__init__.py", line 39, in send_role_info
    im = await draw_pic(uid)
  File "/home/bot/gsuid_core/gsuid_core/plugins/GenshinUID/GenshinUID/genshinuid_roleinfo/draw_roleinfo_card.py", line 128, in draw_pic
    raw_data = await mys_api.get_info(uid, None)
  File "/home/bot/gsuid_core/gsuid_core/utils/api/mys/request.py", line 590, in get_info
    data = await self.simple_mys_req('PLAYER_INFO_URL', uid, cookie=ck)
  File "/home/bot/gsuid_core/gsuid_core/utils/api/mys/request.py", line 293, in simple_mys_req
    data = await self._mys_request(
  File "/home/bot/gsuid_core/gsuid_core/utils/api/mys/request.py", line 402, in _mys_request
    f"Mozilla/5.0 (Linux; Android 13; {df[1]} {df[3]}"
IndexError: list index out of range

**Comment by KimigaiiWuyi** [comment]
是使用apk抓的信息嘛

**Comment by YingLing3** [comment]
> 是使用apk抓的信息嘛

自己抓的，然后模仿文档示例mys设备登录{"fp":"xxxxx","device_id":"xxxx-xxxx-xxxxxxx-xxxx"}
然后也报错，数据库默认存了Unknown/Unknown/Unknown

**Comment by KimigaiiWuyi** [comment]
> > 是使用apk抓的信息嘛
> 
> 自己抓的，然后模仿文档示例mys设备登录{"fp":"xxxxx","device_id":"xxxx-xxxx-xxxxxxx-xxxx"} 然后也报错，数据库默认存了Unknown/Unknown/Unknown

这块文档/gscore有误，应该填入
{"fp":"xxxxx","device_id":"xxxx-xxxx-xxxxxxx-xxxx", "device_info":"Unknown/Unknown/Unknown/Unknown"}

或者能自己抓到device_info替换也行
或者直接用apk，最稳的方式
