### ISSUE TITLE
活动列表报错

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#63]
```
12-25 16:01:29 [SUCCESS] nonebot | CQHTTP 3436954762 | [message.group.normal]: Message -837765519 from 3076823485@[群:1158894874] "活动列表"
12-25 16:01:29 [INFO] nonebot | Event will be handled by <Matcher from GenshinUID, type=message, priority=6, temp=False>
12-25 16:01:30 [INFO] nonebot | Matcher <Matcher from GenshinUID, type=message, priority=6, temp=False> running complete
12-25 16:01:30 [ERROR] nonebot | Running matcher <Matcher from GenshinUID, type=message, priority=6, temp=False> failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nb_cli\commands\main.py", line 26, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nb_cli\handlers\deploy.py", line 22, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 256, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 128, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 156, in _run_matcher
    await matcher.run(bot, event, state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\matcher.py", line 597, in run
    await handler(self, bot, event, self.state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\handler.py", line 64, in __call__
    await self.func(
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2\nonebot2/plugins\GenshinUID\__init__.py", line 212, in _
    await draw_event_pic()
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2\nonebot2/plugins\GenshinUID\getImg.py", line 1329, in draw_event_pic
    base_draw.text((540, 300 + 45 + 390 + (390+90)*index+1), value["act_begin_time"] + " —— " + value["act_end_time"], (255,255,255), ys_font(42), anchor="mm")
KeyError: 'act_begin_time'
```

**Comment by KimigaiiWuyi** [comment]
看起来像是匹配出了问题，很遗憾因为ban掉国内vps之后，我现在也没有办法研究是哪一个event没有匹配到

**Comment by KimigaiiWuyi** [comment]
已修。
