### ISSUE TITLE
【bug？】AttributeError: 'dict' object has no attribute 'data'

### ISSUE THREAD

**Issue by passerdhr** [KimigaiiWuyi/GenshinUID#651]
用的是LLonebot+nonebot2
包括扫码登录、ck帮助在内的命令会报错并无法正常工作，
```
08-31 04:53:21 [INFO] gsuid_core.handler | [Raw] raw_text=ck帮助, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=bot, msg_id=-2147477195, user_type=group, group_id=x, user_id=admin, user_pm=0, content=[Message(type='text', data='ck帮助')],
08-31 04:53:21 [INFO] gsuid_core.handler | [Trigger] 消息 「ck帮助」 触发 「fullmatch」 类型触发器, 关键词: 「ck帮助」
08-31 04:53:21 [INFO] gsuid_core.handler | [Command] command=ck帮助, text=
08-31 04:53:21 [INFO] gsuid_core.bot | [发送消息to] onebot - group - q
```

```
08-31 04:53:21 [SUCCESS] nonebot | OneBot V11 bot | [message.group.normal]: Message -y from admin@[群:q] 'ck帮助'
08-31 04:53:21 [ERROR] GenshinUID | 'dict' object has no attribute 'data'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\client.py", line 169, in recv_msg
    await onebot_send(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\client.py", line 686, in onebot_send
    result_msg = await to_msg(content)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\client.py", line 661, in to_msg
    await to_msg(_c.data),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\GenshinUID\client.py", line 646, in to_msg
    if _c.data:
AttributeError: 'dict' object has no attribute 'data'
```

**Comment by KimigaiiWuyi** [comment]
已修复，请尝试更新nb2端的插件`nonebot-plugin-genshinuid`至`4.7.1`版本，应该可以解决

**Comment by passerdhr** [comment]
好像还是有点小问题？
更新后使用ck帮助会出现
![Snipaste_2024-08-31_13-31-59](https://github.com/user-attachments/assets/238a92b8-5b68-4b49-9cd4-18a02028c5c2)
```
08-31 13:30:20 [SUCCESS] nonebot | OneBot V11 bot | [message.group.normal]: Message 1355720054 from admin@[ 群:q] 'ck帮助'
08-31 13:30:20 [DEBUG] nonebot | Checking for matchers in priority 1...
08-31 13:30:20 [DEBUG] nonebot | Checking for matchers in priority 999...
08-31 13:30:20 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID, lineno=28)
08-31 13:30:20 [DEBUG] nonebot | Running Matcher(type='message', module=GenshinUID, lineno=28)
08-31 13:30:20 [DEBUG] nonebot | Running handler Dependent(call=get_all_message)
08-31 13:30:20 [DEBUG] GenshinUID | [message.group.normal]: Message 1355720054 from admin@[群:q] 'ck帮助'
08-31 13:30:20 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot
08-31 13:30:20 [INFO] nonebot | Matcher(type='message', module=GenshinUID, lineno=28) running complete
08-31 13:30:20 [DEBUG] nonebot | Stop event propagation
08-31 13:30:20 [DEBUG] nonebot | Checking for matchers completed
08-31 13:30:20 [INFO] GenshinUID | 【接收】[gsuid-core]: onebot - group - q
08-31 13:30:20 [DEBUG] nonebot | OneBot V11 | Calling API send_group_forward_msg
08-31 13:30:21 [DEBUG] nonebot | OneBot V11 | Calling API send_group_msg
08-31 13:30:21 [ERROR] GenshinUID | ActionFailed(status='failed', retcode=1200, data=None, message='消息体无法解析，请检查是否发送了不支持的消息类型', wording='消息体无法解析，请检查是否发送了不支持的消息类型', echo='2')
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\GenshinUID\client.py", line 169, in recv_msg
    await onebot_send(
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\GenshinUID\client.py", line 691, in onebot_send
    await bot.call_api(
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='消息体无法解析，请检查是否发送了不支持的消息类型', wording='消息体无法解析，请检查是否发送了不支持的消息类型', echo='2')
``` 
然后私聊bor发送“扫码登录”无效，查看qqnt发现有一临时对话
![Snipaste_2024-08-31_14-00-59](https://github.com/user-attachments/assets/925d6cb8-8d91-4f97-9f8e-a77d7367d13b)

报错信息如下
```
08-31 13:58:31 [DEBUG] GenshinUID | [message.private.friend]: Message 423827545 from admin '扫码登录'
08-31 13:58:31 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot
08-31 13:58:31 [INFO] nonebot | Matcher(type='message', module=GenshinUID, lineno=28) running complete
08-31 13:58:31 [DEBUG] nonebot | Stop event propagation
08-31 13:58:31 [DEBUG] nonebot | Checking for matchers completed
08-31 13:58:31 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
08-31 13:58:31 [INFO] GenshinUID | 开始执行[扫码登陆]
08-31 13:58:31 [INFO] GenshinUID | 【接收】[gsuid-core]: onebot - direct - admin
08-31 13:58:31 [DEBUG] nonebot | OneBot V11 | Calling API send_private_forward_msg
08-31 13:58:38 [ERROR] GenshinUID | ActionFailed(status='failed', retcode=1200, data=None, message='发送转发消息失败 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/multiForwardMsgWithComment ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 0,\n    "errMsg": "success"\n}\n', wording='发送转发消息失败 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/multiForwardMsgWithComment ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 0,\n    "errMsg": "success"\n}\n', echo='42')
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\GenshinUID\client.py", line 169, in recv_msg
    await onebot_send(
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\GenshinUID\client.py", line 689, in onebot_send
    result_msg = await to_msg(content)
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\GenshinUID\client.py", line 662, in to_msg
    await _send_node(
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\GenshinUID\client.py", line 683, in _send_node
    await bot.call_api(
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\Administrator\mhybot\.venv\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='发送转发消息失败 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/multiForwardMsgWithComment ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 0,\n    "errMsg": "success"\n}\n', wording='发送转发消息失败 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/multiForwardMsgWithComment ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 0,\n    "errMsg": "success"\n}\n', echo='42')
```

**Comment by passerdhr** [comment]
在群内发送扫码登陆可以正常使用，好像是只有私聊会出现这种情况？

**Comment by KimigaiiWuyi** [comment]
消息体无法解析的问题已修复，请尝试更新nb2端的插件`nonebot-plugin-genshinuid`至`4.7.2`版本，应该可以解决。

---

另外的私聊问题我无法复现，我使用`NapCat`多次测试私聊和群聊合并转发，并无区别，均无报错。
私聊合并转发不支持临时消息，如果是临时消息的话，请加Bot好友后处理。
你也可以进入gscore的网页控制台，选择适合的处理合并转发的类型，支持`合并为一条消息`,`视为多条消息`,`合并转发`几种不同的发送类型，也许可以满足你的需求。

**Comment by passerdhr** [comment]
那就大概是qqnt+llonebot的问题了，我换napcat试试
感谢
